-- 01_build_silver_all_9.sql
-- Build conformed Silver layer from Bronze tables (all 9 source entities)

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE FINANCE_DB;
USE SCHEMA SILVER;

-- ---------------------------------------------------------------------
-- 1) Silver table DDL
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS SILVER.SLV_ORDERS (
  ORDER_ID STRING,
  CUSTOMER_ID STRING,
  ORDER_STATUS STRING,
  ORDER_PURCHASE_TS TIMESTAMP_NTZ,
  ORDER_APPROVED_TS TIMESTAMP_NTZ,
  ORDER_DELIVERED_CARRIER_TS TIMESTAMP_NTZ,
  ORDER_DELIVERED_CUSTOMER_TS TIMESTAMP_NTZ,
  ORDER_ESTIMATED_DELIVERY_TS TIMESTAMP_NTZ,
  DELIVERY_DELAY_DAYS NUMBER,
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS SILVER.SLV_ORDER_ITEMS (
  ORDER_ID STRING,
  ORDER_ITEM_ID NUMBER,
  PRODUCT_ID STRING,
  SELLER_ID STRING,
  SHIPPING_LIMIT_TS TIMESTAMP_NTZ,
  PRICE NUMBER(18,2),
  FREIGHT_VALUE NUMBER(18,2),
  REVENUE NUMBER(18,2),
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS SILVER.SLV_CUSTOMERS (
  CUSTOMER_ID STRING,
  CUSTOMER_UNIQUE_ID STRING,
  CUSTOMER_ZIP_CODE_PREFIX STRING,
  CUSTOMER_CITY STRING,
  CUSTOMER_STATE STRING,
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS SILVER.SLV_SELLERS (
  SELLER_ID STRING,
  SELLER_ZIP_CODE_PREFIX STRING,
  SELLER_CITY STRING,
  SELLER_STATE STRING,
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS SILVER.SLV_PRODUCTS (
  PRODUCT_ID STRING,
  PRODUCT_CATEGORY_NAME STRING,
  PRODUCT_CATEGORY_NAME_ENGLISH STRING,
  PRODUCT_NAME_LENGTH NUMBER,
  PRODUCT_DESCRIPTION_LENGTH NUMBER,
  PRODUCT_PHOTOS_QTY NUMBER,
  PRODUCT_WEIGHT_G NUMBER,
  PRODUCT_LENGTH_CM NUMBER,
  PRODUCT_HEIGHT_CM NUMBER,
  PRODUCT_WIDTH_CM NUMBER,
  PRODUCT_VOLUME_CM3 NUMBER,
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS SILVER.SLV_ORDER_PAYMENTS (
  ORDER_ID STRING,
  PAYMENT_SEQUENTIAL NUMBER,
  PAYMENT_TYPE STRING,
  PAYMENT_INSTALLMENTS NUMBER,
  PAYMENT_VALUE NUMBER(18,2),
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS SILVER.SLV_ORDER_REVIEWS (
  REVIEW_ID STRING,
  ORDER_ID STRING,
  REVIEW_SCORE NUMBER,
  REVIEW_COMMENT_TITLE STRING,
  REVIEW_COMMENT_MESSAGE STRING,
  REVIEW_CREATION_TS TIMESTAMP_NTZ,
  REVIEW_ANSWER_TS TIMESTAMP_NTZ,
  REVIEW_RESPONSE_HOURS NUMBER(18,2),
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS SILVER.SLV_GEOLOCATION (
  GEOLOCATION_ZIP_CODE_PREFIX STRING,
  GEOLOCATION_LAT NUMBER(18,8),
  GEOLOCATION_LNG NUMBER(18,8),
  GEOLOCATION_CITY STRING,
  GEOLOCATION_STATE STRING,
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ
);

-- ---------------------------------------------------------------------
-- 2) Deterministic reload for learning runs
-- ---------------------------------------------------------------------

TRUNCATE TABLE SILVER.SLV_ORDERS;
TRUNCATE TABLE SILVER.SLV_ORDER_ITEMS;
TRUNCATE TABLE SILVER.SLV_CUSTOMERS;
TRUNCATE TABLE SILVER.SLV_SELLERS;
TRUNCATE TABLE SILVER.SLV_PRODUCTS;
TRUNCATE TABLE SILVER.SLV_ORDER_PAYMENTS;
TRUNCATE TABLE SILVER.SLV_ORDER_REVIEWS;
TRUNCATE TABLE SILVER.SLV_GEOLOCATION;

-- ---------------------------------------------------------------------
-- 3) Bronze -> Silver transformations
-- ---------------------------------------------------------------------

INSERT INTO SILVER.SLV_ORDERS
SELECT
  ORDER_ID,
  CUSTOMER_ID,
  LOWER(TRIM(ORDER_STATUS)) AS ORDER_STATUS,
  ORDER_PURCHASE_TS,
  ORDER_APPROVED_TS,
  ORDER_DELIVERED_CARRIER_TS,
  ORDER_DELIVERED_CUSTOMER_TS,
  ORDER_ESTIMATED_DELIVERY_TS,
  DATEDIFF('day', ORDER_ESTIMATED_DELIVERY_TS::DATE, ORDER_DELIVERED_CUSTOMER_TS::DATE) AS DELIVERY_DELAY_DAYS,
  SRC_FILENAME,
  LOAD_TS
FROM BRONZE.BRZ_ORDERS
WHERE ORDER_ID IS NOT NULL;

INSERT INTO SILVER.SLV_ORDER_ITEMS
SELECT
  ORDER_ID,
  ORDER_ITEM_ID,
  PRODUCT_ID,
  SELLER_ID,
  SHIPPING_LIMIT_TS,
  PRICE,
  FREIGHT_VALUE,
  COALESCE(PRICE, 0) + COALESCE(FREIGHT_VALUE, 0) AS REVENUE,
  SRC_FILENAME,
  LOAD_TS
FROM BRONZE.BRZ_ORDER_ITEMS
WHERE ORDER_ID IS NOT NULL;

INSERT INTO SILVER.SLV_CUSTOMERS
SELECT
  CUSTOMER_ID,
  CUSTOMER_UNIQUE_ID,
  CUSTOMER_ZIP_CODE_PREFIX,
  INITCAP(TRIM(CUSTOMER_CITY)) AS CUSTOMER_CITY,
  UPPER(TRIM(CUSTOMER_STATE)) AS CUSTOMER_STATE,
  SRC_FILENAME,
  LOAD_TS
FROM BRONZE.BRZ_CUSTOMERS
WHERE CUSTOMER_ID IS NOT NULL;

INSERT INTO SILVER.SLV_SELLERS
SELECT
  SELLER_ID,
  SELLER_ZIP_CODE_PREFIX,
  INITCAP(TRIM(SELLER_CITY)) AS SELLER_CITY,
  UPPER(TRIM(SELLER_STATE)) AS SELLER_STATE,
  SRC_FILENAME,
  LOAD_TS
FROM BRONZE.BRZ_SELLERS
WHERE SELLER_ID IS NOT NULL;

INSERT INTO SILVER.SLV_PRODUCTS
SELECT
  p.PRODUCT_ID,
  p.PRODUCT_CATEGORY_NAME,
  t.PRODUCT_CATEGORY_NAME_ENGLISH,
  p.PRODUCT_NAME_LENGTH,
  p.PRODUCT_DESCRIPTION_LENGTH,
  p.PRODUCT_PHOTOS_QTY,
  p.PRODUCT_WEIGHT_G,
  p.PRODUCT_LENGTH_CM,
  p.PRODUCT_HEIGHT_CM,
  p.PRODUCT_WIDTH_CM,
  COALESCE(p.PRODUCT_LENGTH_CM, 0) * COALESCE(p.PRODUCT_HEIGHT_CM, 0) * COALESCE(p.PRODUCT_WIDTH_CM, 0) AS PRODUCT_VOLUME_CM3,
  p.SRC_FILENAME,
  p.LOAD_TS
FROM BRONZE.BRZ_PRODUCTS p
LEFT JOIN BRONZE.BRZ_PRODUCT_CATEGORY_TRANSLATION t
  ON p.PRODUCT_CATEGORY_NAME = t.PRODUCT_CATEGORY_NAME
WHERE p.PRODUCT_ID IS NOT NULL;

INSERT INTO SILVER.SLV_ORDER_PAYMENTS
SELECT
  ORDER_ID,
  PAYMENT_SEQUENTIAL,
  LOWER(TRIM(PAYMENT_TYPE)) AS PAYMENT_TYPE,
  PAYMENT_INSTALLMENTS,
  PAYMENT_VALUE,
  SRC_FILENAME,
  LOAD_TS
FROM BRONZE.BRZ_ORDER_PAYMENTS
WHERE ORDER_ID IS NOT NULL;

INSERT INTO SILVER.SLV_ORDER_REVIEWS
SELECT
  REVIEW_ID,
  ORDER_ID,
  REVIEW_SCORE,
  REVIEW_COMMENT_TITLE,
  REVIEW_COMMENT_MESSAGE,
  REVIEW_CREATION_TS,
  REVIEW_ANSWER_TS,
  DATEDIFF('minute', REVIEW_CREATION_TS, REVIEW_ANSWER_TS) / 60.0 AS REVIEW_RESPONSE_HOURS,
  SRC_FILENAME,
  LOAD_TS
FROM BRONZE.BRZ_ORDER_REVIEWS
WHERE ORDER_ID IS NOT NULL;

INSERT INTO SILVER.SLV_GEOLOCATION
SELECT
  GEOLOCATION_ZIP_CODE_PREFIX,
  GEOLOCATION_LAT,
  GEOLOCATION_LNG,
  INITCAP(TRIM(GEOLOCATION_CITY)) AS GEOLOCATION_CITY,
  UPPER(TRIM(GEOLOCATION_STATE)) AS GEOLOCATION_STATE,
  SRC_FILENAME,
  LOAD_TS
FROM BRONZE.BRZ_GEOLOCATION;

-- ---------------------------------------------------------------------
-- 4) Quick validation: Bronze vs Silver row counts
-- ---------------------------------------------------------------------

SELECT 'BRZ_ORDERS' AS table_name, COUNT(*) AS row_count FROM BRONZE.BRZ_ORDERS
UNION ALL SELECT 'SLV_ORDERS', COUNT(*) FROM SILVER.SLV_ORDERS
UNION ALL SELECT 'BRZ_ORDER_ITEMS', COUNT(*) FROM BRONZE.BRZ_ORDER_ITEMS
UNION ALL SELECT 'SLV_ORDER_ITEMS', COUNT(*) FROM SILVER.SLV_ORDER_ITEMS
UNION ALL SELECT 'BRZ_CUSTOMERS', COUNT(*) FROM BRONZE.BRZ_CUSTOMERS
UNION ALL SELECT 'SLV_CUSTOMERS', COUNT(*) FROM SILVER.SLV_CUSTOMERS
UNION ALL SELECT 'BRZ_SELLERS', COUNT(*) FROM BRONZE.BRZ_SELLERS
UNION ALL SELECT 'SLV_SELLERS', COUNT(*) FROM SILVER.SLV_SELLERS
UNION ALL SELECT 'BRZ_PRODUCTS', COUNT(*) FROM BRONZE.BRZ_PRODUCTS
UNION ALL SELECT 'SLV_PRODUCTS', COUNT(*) FROM SILVER.SLV_PRODUCTS
UNION ALL SELECT 'BRZ_ORDER_PAYMENTS', COUNT(*) FROM BRONZE.BRZ_ORDER_PAYMENTS
UNION ALL SELECT 'SLV_ORDER_PAYMENTS', COUNT(*) FROM SILVER.SLV_ORDER_PAYMENTS
UNION ALL SELECT 'BRZ_ORDER_REVIEWS', COUNT(*) FROM BRONZE.BRZ_ORDER_REVIEWS
UNION ALL SELECT 'SLV_ORDER_REVIEWS', COUNT(*) FROM SILVER.SLV_ORDER_REVIEWS
UNION ALL SELECT 'BRZ_GEOLOCATION', COUNT(*) FROM BRONZE.BRZ_GEOLOCATION
UNION ALL SELECT 'SLV_GEOLOCATION', COUNT(*) FROM SILVER.SLV_GEOLOCATION
ORDER BY 1;
