USE DATABASE FINANCE_DB;
USE SCHEMA SILVER;

TRUNCATE TABLE SILVER.SLV_ORDERS;

INSERT INTO SILVER.SLV_ORDERS
SELECT
  ORDER_ID,
  CUSTOMER_ID,
  LOWER(TRIM(ORDER_STATUS)) AS ORDER_STATUS,
  ORDER_PURCHASE_TS,
  ORDER_APPROVED_TS,
  ORDER_DELIVERED_CARRIER_TS,
  ORDER_DELIVERED_CUSTOMER_TS,
  ORDER_ESTIMATED_DELIVERY_TS,
  DATEDIFF('day', ORDER_ESTIMATED_DELIVERY_TS::DATE, ORDER_DELIVERED_CUSTOMER_TS::DATE) AS DELIVERY_DELAY_DAYS,
  SRC_FILENAME,
  LOAD_TS
FROM BRONZE.BRZ_ORDERS
WHERE ORDER_ID IS NOT NULL;
