USE DATABASE FINANCE_DB;
USE SCHEMA SILVER;

TRUNCATE TABLE SILVER.SLV_ORDER_ITEMS;

INSERT INTO SILVER.SLV_ORDER_ITEMS
SELECT
  ORDER_ID,
  ORDER_ITEM_ID,
  PRODUCT_ID,
  SELLER_ID,
  SHIPPING_LIMIT_TS,
  PRICE,
  FREIGHT_VALUE,
  COALESCE(PRICE, 0) + COALESCE(FREIGHT_VALUE, 0) AS REVENUE,
  SRC_FILENAME,
  LOAD_TS
FROM BRONZE.BRZ_ORDER_ITEMS
WHERE ORDER_ID IS NOT NULL;
