USE DATABASE FINANCE_DB;
USE SCHEMA SILVER;

TRUNCATE TABLE SILVER.SLV_CUSTOMERS;

INSERT INTO SILVER.SLV_CUSTOMERS
SELECT
  CUSTOMER_ID,
  CUSTOMER_UNIQUE_ID,
  CUSTOMER_ZIP_CODE_PREFIX,
  INITCAP(TRIM(CUSTOMER_CITY)) AS CUSTOMER_CITY,
  UPPER(TRIM(CUSTOMER_STATE)) AS CUSTOMER_STATE,
  SRC_FILENAME,
  LOAD_TS
FROM BRONZE.BRZ_CUSTOMERS
WHERE CUSTOMER_ID IS NOT NULL;
