USE DATABASE FINANCE_DB;
USE SCHEMA SILVER;

TRUNCATE TABLE SILVER.SLV_SELLERS;

INSERT INTO SILVER.SLV_SELLERS
SELECT
  SELLER_ID,
  SELLER_ZIP_CODE_PREFIX,
  INITCAP(TRIM(SELLER_CITY)) AS SELLER_CITY,
  UPPER(TRIM(SELLER_STATE)) AS SELLER_STATE,
  SRC_FILENAME,
  LOAD_TS
FROM BRONZE.BRZ_SELLERS
WHERE SELLER_ID IS NOT NULL;
