USE DATABASE FINANCE_DB;
USE SCHEMA SILVER;

TRUNCATE TABLE SILVER.SLV_PRODUCTS;

INSERT INTO SILVER.SLV_PRODUCTS
SELECT
  p.PRODUCT_ID,
  p.PRODUCT_CATEGORY_NAME,
  t.PRODUCT_CATEGORY_NAME_ENGLISH,
  p.PRODUCT_NAME_LENGTH,
  p.PRODUCT_DESCRIPTION_LENGTH,
  p.PRODUCT_PHOTOS_QTY,
  p.PRODUCT_WEIGHT_G,
  p.PRODUCT_LENGTH_CM,
  p.PRODUCT_HEIGHT_CM,
  p.PRODUCT_WIDTH_CM,
  COALESCE(p.PRODUCT_LENGTH_CM, 0) * COALESCE(p.PRODUCT_HEIGHT_CM, 0) * COALESCE(p.PRODUCT_WIDTH_CM, 0) AS PRODUCT_VOLUME_CM3,
  p.SRC_FILENAME,
  p.LOAD_TS
FROM BRONZE.BRZ_PRODUCTS p
LEFT JOIN BRONZE.BRZ_PRODUCT_CATEGORY_TRANSLATION t
  ON p.PRODUCT_CATEGORY_NAME = t.PRODUCT_CATEGORY_NAME
WHERE p.PRODUCT_ID IS NOT NULL;
