USE DATABASE FINANCE_DB;
USE SCHEMA SILVER;

TRUNCATE TABLE SILVER.SLV_ORDER_PAYMENTS;

INSERT INTO SILVER.SLV_ORDER_PAYMENTS
SELECT
  ORDER_ID,
  PAYMENT_SEQUENTIAL,
  LOWER(TRIM(PAYMENT_TYPE)) AS PAYMENT_TYPE,
  PAYMENT_INSTALLMENTS,
  PAYMENT_VALUE,
  SRC_FILENAME,
  LOAD_TS
FROM BRONZE.BRZ_ORDER_PAYMENTS
WHERE ORDER_ID IS NOT NULL;
