USE DATABASE FINANCE_DB;
USE SCHEMA SILVER;

TRUNCATE TABLE SILVER.SLV_ORDER_REVIEWS;

INSERT INTO SILVER.SLV_ORDER_REVIEWS
SELECT
  REVIEW_ID,
  ORDER_ID,
  REVIEW_SCORE,
  REVIEW_COMMENT_TITLE,
  REVIEW_COMMENT_MESSAGE,
  REVIEW_CREATION_TS,
  REVIEW_ANSWER_TS,
  DATEDIFF('minute', REVIEW_CREATION_TS, REVIEW_ANSWER_TS) / 60.0 AS REVIEW_RESPONSE_HOURS,
  SRC_FILENAME,
  LOAD_TS
FROM BRONZE.BRZ_ORDER_REVIEWS
WHERE ORDER_ID IS NOT NULL;
