USE DATABASE FINANCE_DB;
USE SCHEMA SILVER;

TRUNCATE TABLE SILVER.SLV_GEOLOCATION;

INSERT INTO SILVER.SLV_GEOLOCATION
SELECT
  GEOLOCATION_ZIP_CODE_PREFIX,
  GEOLOCATION_LAT,
  GEOLOCATION_LNG,
  INITCAP(TRIM(GEOLOCATION_CITY)) AS GEOLOCATION_CITY,
  UPPER(TRIM(GEOLOCATION_STATE)) AS GEOLOCATION_STATE,
  SRC_FILENAME,
  LOAD_TS
FROM BRONZE.BRZ_GEOLOCATION;
