USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE FINANCE_DB;

CREATE OR REPLACE PROCEDURE FINANCE_DB.SILVER.SP_REBUILD_SILVER()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  TRUNCATE TABLE FINANCE_DB.SILVER.SLV_ORDERS;
  TRUNCATE TABLE FINANCE_DB.SILVER.SLV_ORDER_ITEMS;
  TRUNCATE TABLE FINANCE_DB.SILVER.SLV_CUSTOMERS;
  TRUNCATE TABLE FINANCE_DB.SILVER.SLV_SELLERS;
  TRUNCATE TABLE FINANCE_DB.SILVER.SLV_PRODUCTS;
  TRUNCATE TABLE FINANCE_DB.SILVER.SLV_ORDER_PAYMENTS;
  TRUNCATE TABLE FINANCE_DB.SILVER.SLV_ORDER_REVIEWS;
  TRUNCATE TABLE FINANCE_DB.SILVER.SLV_GEOLOCATION;

  INSERT INTO FINANCE_DB.SILVER.SLV_ORDERS
  SELECT ORDER_ID, CUSTOMER_ID, LOWER(TRIM(ORDER_STATUS)), ORDER_PURCHASE_TS, ORDER_APPROVED_TS,
         ORDER_DELIVERED_CARRIER_TS, ORDER_DELIVERED_CUSTOMER_TS, ORDER_ESTIMATED_DELIVERY_TS,
         DATEDIFF('day', ORDER_ESTIMATED_DELIVERY_TS::DATE, ORDER_DELIVERED_CUSTOMER_TS::DATE),
         SRC_FILENAME, LOAD_TS
  FROM FINANCE_DB.BRONZE.BRZ_ORDERS
  WHERE ORDER_ID IS NOT NULL;

  INSERT INTO FINANCE_DB.SILVER.SLV_ORDER_ITEMS
  SELECT ORDER_ID, ORDER_ITEM_ID, PRODUCT_ID, SELLER_ID, SHIPPING_LIMIT_TS, PRICE, FREIGHT_VALUE,
         COALESCE(PRICE, 0) + COALESCE(FREIGHT_VALUE, 0), SRC_FILENAME, LOAD_TS
  FROM FINANCE_DB.BRONZE.BRZ_ORDER_ITEMS
  WHERE ORDER_ID IS NOT NULL;

  INSERT INTO FINANCE_DB.SILVER.SLV_CUSTOMERS
  SELECT CUSTOMER_ID, CUSTOMER_UNIQUE_ID, CUSTOMER_ZIP_CODE_PREFIX,
         INITCAP(TRIM(CUSTOMER_CITY)), UPPER(TRIM(CUSTOMER_STATE)), SRC_FILENAME, LOAD_TS
  FROM FINANCE_DB.BRONZE.BRZ_CUSTOMERS
  WHERE CUSTOMER_ID IS NOT NULL;

  INSERT INTO FINANCE_DB.SILVER.SLV_SELLERS
  SELECT SELLER_ID, SELLER_ZIP_CODE_PREFIX, INITCAP(TRIM(SELLER_CITY)), UPPER(TRIM(SELLER_STATE)), SRC_FILENAME, LOAD_TS
  FROM FINANCE_DB.BRONZE.BRZ_SELLERS
  WHERE SELLER_ID IS NOT NULL;

  INSERT INTO FINANCE_DB.SILVER.SLV_PRODUCTS
  SELECT p.PRODUCT_ID, p.PRODUCT_CATEGORY_NAME, t.PRODUCT_CATEGORY_NAME_ENGLISH,
         p.PRODUCT_NAME_LENGTH, p.PRODUCT_DESCRIPTION_LENGTH, p.PRODUCT_PHOTOS_QTY,
         p.PRODUCT_WEIGHT_G, p.PRODUCT_LENGTH_CM, p.PRODUCT_HEIGHT_CM, p.PRODUCT_WIDTH_CM,
         COALESCE(p.PRODUCT_LENGTH_CM,0)*COALESCE(p.PRODUCT_HEIGHT_CM,0)*COALESCE(p.PRODUCT_WIDTH_CM,0),
         p.SRC_FILENAME, p.LOAD_TS
  FROM FINANCE_DB.BRONZE.BRZ_PRODUCTS p
  LEFT JOIN FINANCE_DB.BRONZE.BRZ_PRODUCT_CATEGORY_TRANSLATION t
    ON p.PRODUCT_CATEGORY_NAME = t.PRODUCT_CATEGORY_NAME
  WHERE p.PRODUCT_ID IS NOT NULL;

  INSERT INTO FINANCE_DB.SILVER.SLV_ORDER_PAYMENTS
  SELECT ORDER_ID, PAYMENT_SEQUENTIAL, LOWER(TRIM(PAYMENT_TYPE)), PAYMENT_INSTALLMENTS,
         PAYMENT_VALUE, SRC_FILENAME, LOAD_TS
  FROM FINANCE_DB.BRONZE.BRZ_ORDER_PAYMENTS
  WHERE ORDER_ID IS NOT NULL;

  INSERT INTO FINANCE_DB.SILVER.SLV_ORDER_REVIEWS
  SELECT REVIEW_ID, ORDER_ID, REVIEW_SCORE, REVIEW_COMMENT_TITLE, REVIEW_COMMENT_MESSAGE,
         REVIEW_CREATION_TS, REVIEW_ANSWER_TS,
         DATEDIFF('minute', REVIEW_CREATION_TS, REVIEW_ANSWER_TS) / 60.0,
         SRC_FILENAME, LOAD_TS
  FROM FINANCE_DB.BRONZE.BRZ_ORDER_REVIEWS
  WHERE ORDER_ID IS NOT NULL;

  INSERT INTO FINANCE_DB.SILVER.SLV_GEOLOCATION
  SELECT GEOLOCATION_ZIP_CODE_PREFIX, GEOLOCATION_LAT, GEOLOCATION_LNG,
         INITCAP(TRIM(GEOLOCATION_CITY)), UPPER(TRIM(GEOLOCATION_STATE)),
         SRC_FILENAME, LOAD_TS
  FROM FINANCE_DB.BRONZE.BRZ_GEOLOCATION;

  RETURN 'SILVER_REBUILT';
END;
$$;
