USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE FINANCE_DB;

CREATE OR REPLACE PROCEDURE FINANCE_DB.SILVER.SP_APPLY_SILVER_INCREMENTAL()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  MERGE INTO FINANCE_DB.SILVER.SLV_ORDERS t
  USING (
    SELECT ORDER_ID, CUSTOMER_ID, LOWER(TRIM(ORDER_STATUS)) AS ORDER_STATUS,
           ORDER_PURCHASE_TS, ORDER_APPROVED_TS, ORDER_DELIVERED_CARRIER_TS,
           ORDER_DELIVERED_CUSTOMER_TS, ORDER_ESTIMATED_DELIVERY_TS,
           DATEDIFF('day', ORDER_ESTIMATED_DELIVERY_TS::DATE, ORDER_DELIVERED_CUSTOMER_TS::DATE) AS DELIVERY_DELAY_DAYS,
           SRC_FILENAME, LOAD_TS
    FROM FINANCE_DB.BRONZE.STR_BRZ_ORDERS
    WHERE METADATA$ACTION IN ('INSERT','UPDATE')
  ) s
  ON t.ORDER_ID = s.ORDER_ID
  WHEN MATCHED THEN UPDATE SET
    CUSTOMER_ID = s.CUSTOMER_ID,
    ORDER_STATUS = s.ORDER_STATUS,
    ORDER_PURCHASE_TS = s.ORDER_PURCHASE_TS,
    ORDER_APPROVED_TS = s.ORDER_APPROVED_TS,
    ORDER_DELIVERED_CARRIER_TS = s.ORDER_DELIVERED_CARRIER_TS,
    ORDER_DELIVERED_CUSTOMER_TS = s.ORDER_DELIVERED_CUSTOMER_TS,
    ORDER_ESTIMATED_DELIVERY_TS = s.ORDER_ESTIMATED_DELIVERY_TS,
    DELIVERY_DELAY_DAYS = s.DELIVERY_DELAY_DAYS,
    SRC_FILENAME = s.SRC_FILENAME,
    LOAD_TS = s.LOAD_TS
  WHEN NOT MATCHED THEN INSERT (
    ORDER_ID, CUSTOMER_ID, ORDER_STATUS, ORDER_PURCHASE_TS, ORDER_APPROVED_TS,
    ORDER_DELIVERED_CARRIER_TS, ORDER_DELIVERED_CUSTOMER_TS, ORDER_ESTIMATED_DELIVERY_TS,
    DELIVERY_DELAY_DAYS, SRC_FILENAME, LOAD_TS
  ) VALUES (
    s.ORDER_ID, s.CUSTOMER_ID, s.ORDER_STATUS, s.ORDER_PURCHASE_TS, s.ORDER_APPROVED_TS,
    s.ORDER_DELIVERED_CARRIER_TS, s.ORDER_DELIVERED_CUSTOMER_TS, s.ORDER_ESTIMATED_DELIVERY_TS,
    s.DELIVERY_DELAY_DAYS, s.SRC_FILENAME, s.LOAD_TS
  );

  MERGE INTO FINANCE_DB.SILVER.SLV_ORDER_ITEMS t
  USING (
    SELECT ORDER_ID, ORDER_ITEM_ID, PRODUCT_ID, SELLER_ID, SHIPPING_LIMIT_TS,
           PRICE, FREIGHT_VALUE, COALESCE(PRICE,0) + COALESCE(FREIGHT_VALUE,0) AS REVENUE,
           SRC_FILENAME, LOAD_TS
    FROM FINANCE_DB.BRONZE.STR_BRZ_ORDER_ITEMS
    WHERE METADATA$ACTION IN ('INSERT','UPDATE')
  ) s
  ON t.ORDER_ID = s.ORDER_ID AND t.ORDER_ITEM_ID = s.ORDER_ITEM_ID
  WHEN MATCHED THEN UPDATE SET
    PRODUCT_ID = s.PRODUCT_ID,
    SELLER_ID = s.SELLER_ID,
    SHIPPING_LIMIT_TS = s.SHIPPING_LIMIT_TS,
    PRICE = s.PRICE,
    FREIGHT_VALUE = s.FREIGHT_VALUE,
    REVENUE = s.REVENUE,
    SRC_FILENAME = s.SRC_FILENAME,
    LOAD_TS = s.LOAD_TS
  WHEN NOT MATCHED THEN INSERT (
    ORDER_ID, ORDER_ITEM_ID, PRODUCT_ID, SELLER_ID, SHIPPING_LIMIT_TS,
    PRICE, FREIGHT_VALUE, REVENUE, SRC_FILENAME, LOAD_TS
  ) VALUES (
    s.ORDER_ID, s.ORDER_ITEM_ID, s.PRODUCT_ID, s.SELLER_ID, s.SHIPPING_LIMIT_TS,
    s.PRICE, s.FREIGHT_VALUE, s.REVENUE, s.SRC_FILENAME, s.LOAD_TS
  );

  MERGE INTO FINANCE_DB.SILVER.SLV_CUSTOMERS t
  USING (
    SELECT CUSTOMER_ID, CUSTOMER_UNIQUE_ID, CUSTOMER_ZIP_CODE_PREFIX,
           INITCAP(TRIM(CUSTOMER_CITY)) AS CUSTOMER_CITY, UPPER(TRIM(CUSTOMER_STATE)) AS CUSTOMER_STATE,
           SRC_FILENAME, LOAD_TS
    FROM FINANCE_DB.BRONZE.STR_BRZ_CUSTOMERS
    WHERE METADATA$ACTION IN ('INSERT','UPDATE')
  ) s
  ON t.CUSTOMER_ID = s.CUSTOMER_ID
  WHEN MATCHED THEN UPDATE SET
    CUSTOMER_UNIQUE_ID = s.CUSTOMER_UNIQUE_ID,
    CUSTOMER_ZIP_CODE_PREFIX = s.CUSTOMER_ZIP_CODE_PREFIX,
    CUSTOMER_CITY = s.CUSTOMER_CITY,
    CUSTOMER_STATE = s.CUSTOMER_STATE,
    SRC_FILENAME = s.SRC_FILENAME,
    LOAD_TS = s.LOAD_TS
  WHEN NOT MATCHED THEN INSERT (
    CUSTOMER_ID, CUSTOMER_UNIQUE_ID, CUSTOMER_ZIP_CODE_PREFIX, CUSTOMER_CITY, CUSTOMER_STATE, SRC_FILENAME, LOAD_TS
  ) VALUES (
    s.CUSTOMER_ID, s.CUSTOMER_UNIQUE_ID, s.CUSTOMER_ZIP_CODE_PREFIX, s.CUSTOMER_CITY, s.CUSTOMER_STATE, s.SRC_FILENAME, s.LOAD_TS
  );

  MERGE INTO FINANCE_DB.SILVER.SLV_SELLERS t
  USING (
    SELECT SELLER_ID, SELLER_ZIP_CODE_PREFIX, INITCAP(TRIM(SELLER_CITY)) AS SELLER_CITY,
           UPPER(TRIM(SELLER_STATE)) AS SELLER_STATE, SRC_FILENAME, LOAD_TS
    FROM FINANCE_DB.BRONZE.STR_BRZ_SELLERS
    WHERE METADATA$ACTION IN ('INSERT','UPDATE')
  ) s
  ON t.SELLER_ID = s.SELLER_ID
  WHEN MATCHED THEN UPDATE SET
    SELLER_ZIP_CODE_PREFIX = s.SELLER_ZIP_CODE_PREFIX,
    SELLER_CITY = s.SELLER_CITY,
    SELLER_STATE = s.SELLER_STATE,
    SRC_FILENAME = s.SRC_FILENAME,
    LOAD_TS = s.LOAD_TS
  WHEN NOT MATCHED THEN INSERT (
    SELLER_ID, SELLER_ZIP_CODE_PREFIX, SELLER_CITY, SELLER_STATE, SRC_FILENAME, LOAD_TS
  ) VALUES (
    s.SELLER_ID, s.SELLER_ZIP_CODE_PREFIX, s.SELLER_CITY, s.SELLER_STATE, s.SRC_FILENAME, s.LOAD_TS
  );

  MERGE INTO FINANCE_DB.SILVER.SLV_PRODUCTS t
  USING (
    SELECT p.PRODUCT_ID, p.PRODUCT_CATEGORY_NAME, tr.PRODUCT_CATEGORY_NAME_ENGLISH,
           p.PRODUCT_NAME_LENGTH, p.PRODUCT_DESCRIPTION_LENGTH, p.PRODUCT_PHOTOS_QTY,
           p.PRODUCT_WEIGHT_G, p.PRODUCT_LENGTH_CM, p.PRODUCT_HEIGHT_CM, p.PRODUCT_WIDTH_CM,
           COALESCE(p.PRODUCT_LENGTH_CM,0)*COALESCE(p.PRODUCT_HEIGHT_CM,0)*COALESCE(p.PRODUCT_WIDTH_CM,0) AS PRODUCT_VOLUME_CM3,
           p.SRC_FILENAME, p.LOAD_TS
    FROM FINANCE_DB.BRONZE.BRZ_PRODUCTS p
    LEFT JOIN FINANCE_DB.BRONZE.BRZ_PRODUCT_CATEGORY_TRANSLATION tr
      ON p.PRODUCT_CATEGORY_NAME = tr.PRODUCT_CATEGORY_NAME
    WHERE p.PRODUCT_ID IN (
      SELECT PRODUCT_ID
      FROM FINANCE_DB.BRONZE.STR_BRZ_PRODUCTS
      WHERE METADATA$ACTION IN ('INSERT','UPDATE')
    )
  ) s
  ON t.PRODUCT_ID = s.PRODUCT_ID
  WHEN MATCHED THEN UPDATE SET
    PRODUCT_CATEGORY_NAME = s.PRODUCT_CATEGORY_NAME,
    PRODUCT_CATEGORY_NAME_ENGLISH = s.PRODUCT_CATEGORY_NAME_ENGLISH,
    PRODUCT_NAME_LENGTH = s.PRODUCT_NAME_LENGTH,
    PRODUCT_DESCRIPTION_LENGTH = s.PRODUCT_DESCRIPTION_LENGTH,
    PRODUCT_PHOTOS_QTY = s.PRODUCT_PHOTOS_QTY,
    PRODUCT_WEIGHT_G = s.PRODUCT_WEIGHT_G,
    PRODUCT_LENGTH_CM = s.PRODUCT_LENGTH_CM,
    PRODUCT_HEIGHT_CM = s.PRODUCT_HEIGHT_CM,
    PRODUCT_WIDTH_CM = s.PRODUCT_WIDTH_CM,
    PRODUCT_VOLUME_CM3 = s.PRODUCT_VOLUME_CM3,
    SRC_FILENAME = s.SRC_FILENAME,
    LOAD_TS = s.LOAD_TS
  WHEN NOT MATCHED THEN INSERT (
    PRODUCT_ID, PRODUCT_CATEGORY_NAME, PRODUCT_CATEGORY_NAME_ENGLISH,
    PRODUCT_NAME_LENGTH, PRODUCT_DESCRIPTION_LENGTH, PRODUCT_PHOTOS_QTY,
    PRODUCT_WEIGHT_G, PRODUCT_LENGTH_CM, PRODUCT_HEIGHT_CM, PRODUCT_WIDTH_CM,
    PRODUCT_VOLUME_CM3, SRC_FILENAME, LOAD_TS
  ) VALUES (
    s.PRODUCT_ID, s.PRODUCT_CATEGORY_NAME, s.PRODUCT_CATEGORY_NAME_ENGLISH,
    s.PRODUCT_NAME_LENGTH, s.PRODUCT_DESCRIPTION_LENGTH, s.PRODUCT_PHOTOS_QTY,
    s.PRODUCT_WEIGHT_G, s.PRODUCT_LENGTH_CM, s.PRODUCT_HEIGHT_CM, s.PRODUCT_WIDTH_CM,
    s.PRODUCT_VOLUME_CM3, s.SRC_FILENAME, s.LOAD_TS
  );

  MERGE INTO FINANCE_DB.SILVER.SLV_ORDER_PAYMENTS t
  USING (
    SELECT ORDER_ID, PAYMENT_SEQUENTIAL, LOWER(TRIM(PAYMENT_TYPE)) AS PAYMENT_TYPE,
           PAYMENT_INSTALLMENTS, PAYMENT_VALUE, SRC_FILENAME, LOAD_TS
    FROM FINANCE_DB.BRONZE.STR_BRZ_ORDER_PAYMENTS
    WHERE METADATA$ACTION IN ('INSERT','UPDATE')
  ) s
  ON t.ORDER_ID = s.ORDER_ID AND t.PAYMENT_SEQUENTIAL = s.PAYMENT_SEQUENTIAL
  WHEN MATCHED THEN UPDATE SET
    PAYMENT_TYPE = s.PAYMENT_TYPE,
    PAYMENT_INSTALLMENTS = s.PAYMENT_INSTALLMENTS,
    PAYMENT_VALUE = s.PAYMENT_VALUE,
    SRC_FILENAME = s.SRC_FILENAME,
    LOAD_TS = s.LOAD_TS
  WHEN NOT MATCHED THEN INSERT (
    ORDER_ID, PAYMENT_SEQUENTIAL, PAYMENT_TYPE, PAYMENT_INSTALLMENTS, PAYMENT_VALUE, SRC_FILENAME, LOAD_TS
  ) VALUES (
    s.ORDER_ID, s.PAYMENT_SEQUENTIAL, s.PAYMENT_TYPE, s.PAYMENT_INSTALLMENTS, s.PAYMENT_VALUE, s.SRC_FILENAME, s.LOAD_TS
  );

  MERGE INTO FINANCE_DB.SILVER.SLV_ORDER_REVIEWS t
  USING (
    SELECT REVIEW_ID, ORDER_ID, REVIEW_SCORE, REVIEW_COMMENT_TITLE, REVIEW_COMMENT_MESSAGE,
           REVIEW_CREATION_TS, REVIEW_ANSWER_TS,
           DATEDIFF('minute', REVIEW_CREATION_TS, REVIEW_ANSWER_TS) / 60.0 AS REVIEW_RESPONSE_HOURS,
           SRC_FILENAME, LOAD_TS
    FROM FINANCE_DB.BRONZE.STR_BRZ_ORDER_REVIEWS
    WHERE METADATA$ACTION IN ('INSERT','UPDATE')
  ) s
  ON t.REVIEW_ID = s.REVIEW_ID
  WHEN MATCHED THEN UPDATE SET
    ORDER_ID = s.ORDER_ID,
    REVIEW_SCORE = s.REVIEW_SCORE,
    REVIEW_COMMENT_TITLE = s.REVIEW_COMMENT_TITLE,
    REVIEW_COMMENT_MESSAGE = s.REVIEW_COMMENT_MESSAGE,
    REVIEW_CREATION_TS = s.REVIEW_CREATION_TS,
    REVIEW_ANSWER_TS = s.REVIEW_ANSWER_TS,
    REVIEW_RESPONSE_HOURS = s.REVIEW_RESPONSE_HOURS,
    SRC_FILENAME = s.SRC_FILENAME,
    LOAD_TS = s.LOAD_TS
  WHEN NOT MATCHED THEN INSERT (
    REVIEW_ID, ORDER_ID, REVIEW_SCORE, REVIEW_COMMENT_TITLE, REVIEW_COMMENT_MESSAGE,
    REVIEW_CREATION_TS, REVIEW_ANSWER_TS, REVIEW_RESPONSE_HOURS, SRC_FILENAME, LOAD_TS
  ) VALUES (
    s.REVIEW_ID, s.ORDER_ID, s.REVIEW_SCORE, s.REVIEW_COMMENT_TITLE, s.REVIEW_COMMENT_MESSAGE,
    s.REVIEW_CREATION_TS, s.REVIEW_ANSWER_TS, s.REVIEW_RESPONSE_HOURS, s.SRC_FILENAME, s.LOAD_TS
  );

  MERGE INTO FINANCE_DB.SILVER.SLV_GEOLOCATION t
  USING (
    SELECT GEOLOCATION_ZIP_CODE_PREFIX, GEOLOCATION_LAT, GEOLOCATION_LNG,
           INITCAP(TRIM(GEOLOCATION_CITY)) AS GEOLOCATION_CITY,
           UPPER(TRIM(GEOLOCATION_STATE)) AS GEOLOCATION_STATE,
           SRC_FILENAME, LOAD_TS
    FROM FINANCE_DB.BRONZE.STR_BRZ_GEOLOCATION
    WHERE METADATA$ACTION IN ('INSERT','UPDATE')
  ) s
  ON t.GEOLOCATION_ZIP_CODE_PREFIX = s.GEOLOCATION_ZIP_CODE_PREFIX
 AND t.GEOLOCATION_LAT = s.GEOLOCATION_LAT
 AND t.GEOLOCATION_LNG = s.GEOLOCATION_LNG
  WHEN MATCHED THEN UPDATE SET
    GEOLOCATION_CITY = s.GEOLOCATION_CITY,
    GEOLOCATION_STATE = s.GEOLOCATION_STATE,
    SRC_FILENAME = s.SRC_FILENAME,
    LOAD_TS = s.LOAD_TS
  WHEN NOT MATCHED THEN INSERT (
    GEOLOCATION_ZIP_CODE_PREFIX, GEOLOCATION_LAT, GEOLOCATION_LNG,
    GEOLOCATION_CITY, GEOLOCATION_STATE, SRC_FILENAME, LOAD_TS
  ) VALUES (
    s.GEOLOCATION_ZIP_CODE_PREFIX, s.GEOLOCATION_LAT, s.GEOLOCATION_LNG,
    s.GEOLOCATION_CITY, s.GEOLOCATION_STATE, s.SRC_FILENAME, s.LOAD_TS
  );

  RETURN 'SILVER_INCREMENTAL_APPLIED';
END;
$$;
