USE DATABASE FINANCE_DB;

SELECT 'BRZ_ORDERS' AS table_name, COUNT(*) AS row_count FROM BRONZE.BRZ_ORDERS
UNION ALL SELECT 'SLV_ORDERS', COUNT(*) FROM SILVER.SLV_ORDERS
UNION ALL SELECT 'BRZ_ORDER_ITEMS', COUNT(*) FROM BRONZE.BRZ_ORDER_ITEMS
UNION ALL SELECT 'SLV_ORDER_ITEMS', COUNT(*) FROM SILVER.SLV_ORDER_ITEMS
UNION ALL SELECT 'BRZ_CUSTOMERS', COUNT(*) FROM BRONZE.BRZ_CUSTOMERS
UNION ALL SELECT 'SLV_CUSTOMERS', COUNT(*) FROM SILVER.SLV_CUSTOMERS
UNION ALL SELECT 'BRZ_SELLERS', COUNT(*) FROM BRONZE.BRZ_SELLERS
UNION ALL SELECT 'SLV_SELLERS', COUNT(*) FROM SILVER.SLV_SELLERS
UNION ALL SELECT 'BRZ_PRODUCTS', COUNT(*) FROM BRONZE.BRZ_PRODUCTS
UNION ALL SELECT 'SLV_PRODUCTS', COUNT(*) FROM SILVER.SLV_PRODUCTS
UNION ALL SELECT 'BRZ_ORDER_PAYMENTS', COUNT(*) FROM BRONZE.BRZ_ORDER_PAYMENTS
UNION ALL SELECT 'SLV_ORDER_PAYMENTS', COUNT(*) FROM SILVER.SLV_ORDER_PAYMENTS
UNION ALL SELECT 'BRZ_ORDER_REVIEWS', COUNT(*) FROM BRONZE.BRZ_ORDER_REVIEWS
UNION ALL SELECT 'SLV_ORDER_REVIEWS', COUNT(*) FROM SILVER.SLV_ORDER_REVIEWS
UNION ALL SELECT 'BRZ_GEOLOCATION', COUNT(*) FROM BRONZE.BRZ_GEOLOCATION
UNION ALL SELECT 'SLV_GEOLOCATION', COUNT(*) FROM SILVER.SLV_GEOLOCATION
ORDER BY 1;
