-- 01_create_file_format_and_stage.sql
-- Define CSV parsing and named stage for raw file ingestion

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE FINANCE_DB;
USE SCHEMA STAGE;

CREATE OR REPLACE FILE FORMAT STAGE.FF_CSV
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  TRIM_SPACE = TRUE
  EMPTY_FIELD_AS_NULL = TRUE
  NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE STAGE.RAW_CSV_STAGE
  FILE_FORMAT = STAGE.FF_CSV;

-- Optional verification
SHOW FILE FORMATS IN SCHEMA FINANCE_DB.STAGE;
SHOW STAGES IN SCHEMA FINANCE_DB.STAGE;
