USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE FINANCE_DB;
USE SCHEMA BRONZE;

CREATE TABLE IF NOT EXISTS BRONZE.BRZ_ORDERS (
  ORDER_ID STRING,
  CUSTOMER_ID STRING,
  ORDER_STATUS STRING,
  ORDER_PURCHASE_TS TIMESTAMP_NTZ,
  ORDER_APPROVED_TS TIMESTAMP_NTZ,
  ORDER_DELIVERED_CARRIER_TS TIMESTAMP_NTZ,
  ORDER_DELIVERED_CUSTOMER_TS TIMESTAMP_NTZ,
  ORDER_ESTIMATED_DELIVERY_TS TIMESTAMP_NTZ,
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS BRONZE.BRZ_ORDER_ITEMS (
  ORDER_ID STRING,
  ORDER_ITEM_ID NUMBER,
  PRODUCT_ID STRING,
  SELLER_ID STRING,
  SHIPPING_LIMIT_TS TIMESTAMP_NTZ,
  PRICE NUMBER(18,2),
  FREIGHT_VALUE NUMBER(18,2),
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS BRONZE.BRZ_CUSTOMERS (
  CUSTOMER_ID STRING,
  CUSTOMER_UNIQUE_ID STRING,
  CUSTOMER_ZIP_CODE_PREFIX STRING,
  CUSTOMER_CITY STRING,
  CUSTOMER_STATE STRING,
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS BRONZE.BRZ_SELLERS (
  SELLER_ID STRING,
  SELLER_ZIP_CODE_PREFIX STRING,
  SELLER_CITY STRING,
  SELLER_STATE STRING,
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS BRONZE.BRZ_PRODUCTS (
  PRODUCT_ID STRING,
  PRODUCT_CATEGORY_NAME STRING,
  PRODUCT_NAME_LENGTH NUMBER,
  PRODUCT_DESCRIPTION_LENGTH NUMBER,
  PRODUCT_PHOTOS_QTY NUMBER,
  PRODUCT_WEIGHT_G NUMBER,
  PRODUCT_LENGTH_CM NUMBER,
  PRODUCT_HEIGHT_CM NUMBER,
  PRODUCT_WIDTH_CM NUMBER,
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS BRONZE.BRZ_PRODUCT_CATEGORY_TRANSLATION (
  PRODUCT_CATEGORY_NAME STRING,
  PRODUCT_CATEGORY_NAME_ENGLISH STRING,
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS BRONZE.BRZ_ORDER_PAYMENTS (
  ORDER_ID STRING,
  PAYMENT_SEQUENTIAL NUMBER,
  PAYMENT_TYPE STRING,
  PAYMENT_INSTALLMENTS NUMBER,
  PAYMENT_VALUE NUMBER(18,2),
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS BRONZE.BRZ_ORDER_REVIEWS (
  REVIEW_ID STRING,
  ORDER_ID STRING,
  REVIEW_SCORE NUMBER,
  REVIEW_COMMENT_TITLE STRING,
  REVIEW_COMMENT_MESSAGE STRING,
  REVIEW_CREATION_TS TIMESTAMP_NTZ,
  REVIEW_ANSWER_TS TIMESTAMP_NTZ,
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS BRONZE.BRZ_GEOLOCATION (
  GEOLOCATION_ZIP_CODE_PREFIX STRING,
  GEOLOCATION_LAT NUMBER(18,8),
  GEOLOCATION_LNG NUMBER(18,8),
  GEOLOCATION_CITY STRING,
  GEOLOCATION_STATE STRING,
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ
);
