-- 01_build_bronze_all_9.sql
-- Build typed Bronze layer from Landing raw tables (all 9 source entities)

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE FINANCE_DB;
USE SCHEMA BRONZE;

-- ---------------------------------------------------------------------
-- 1) Bronze table DDL
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS BRONZE.BRZ_ORDERS (
  ORDER_ID STRING,
  CUSTOMER_ID STRING,
  ORDER_STATUS STRING,
  ORDER_PURCHASE_TS TIMESTAMP_NTZ,
  ORDER_APPROVED_TS TIMESTAMP_NTZ,
  ORDER_DELIVERED_CARRIER_TS TIMESTAMP_NTZ,
  ORDER_DELIVERED_CUSTOMER_TS TIMESTAMP_NTZ,
  ORDER_ESTIMATED_DELIVERY_TS TIMESTAMP_NTZ,
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS BRONZE.BRZ_ORDER_ITEMS (
  ORDER_ID STRING,
  ORDER_ITEM_ID NUMBER,
  PRODUCT_ID STRING,
  SELLER_ID STRING,
  SHIPPING_LIMIT_TS TIMESTAMP_NTZ,
  PRICE NUMBER(18,2),
  FREIGHT_VALUE NUMBER(18,2),
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS BRONZE.BRZ_CUSTOMERS (
  CUSTOMER_ID STRING,
  CUSTOMER_UNIQUE_ID STRING,
  CUSTOMER_ZIP_CODE_PREFIX STRING,
  CUSTOMER_CITY STRING,
  CUSTOMER_STATE STRING,
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS BRONZE.BRZ_SELLERS (
  SELLER_ID STRING,
  SELLER_ZIP_CODE_PREFIX STRING,
  SELLER_CITY STRING,
  SELLER_STATE STRING,
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS BRONZE.BRZ_PRODUCTS (
  PRODUCT_ID STRING,
  PRODUCT_CATEGORY_NAME STRING,
  PRODUCT_NAME_LENGTH NUMBER,
  PRODUCT_DESCRIPTION_LENGTH NUMBER,
  PRODUCT_PHOTOS_QTY NUMBER,
  PRODUCT_WEIGHT_G NUMBER,
  PRODUCT_LENGTH_CM NUMBER,
  PRODUCT_HEIGHT_CM NUMBER,
  PRODUCT_WIDTH_CM NUMBER,
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS BRONZE.BRZ_PRODUCT_CATEGORY_TRANSLATION (
  PRODUCT_CATEGORY_NAME STRING,
  PRODUCT_CATEGORY_NAME_ENGLISH STRING,
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS BRONZE.BRZ_ORDER_PAYMENTS (
  ORDER_ID STRING,
  PAYMENT_SEQUENTIAL NUMBER,
  PAYMENT_TYPE STRING,
  PAYMENT_INSTALLMENTS NUMBER,
  PAYMENT_VALUE NUMBER(18,2),
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS BRONZE.BRZ_ORDER_REVIEWS (
  REVIEW_ID STRING,
  ORDER_ID STRING,
  REVIEW_SCORE NUMBER,
  REVIEW_COMMENT_TITLE STRING,
  REVIEW_COMMENT_MESSAGE STRING,
  REVIEW_CREATION_TS TIMESTAMP_NTZ,
  REVIEW_ANSWER_TS TIMESTAMP_NTZ,
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS BRONZE.BRZ_GEOLOCATION (
  GEOLOCATION_ZIP_CODE_PREFIX STRING,
  GEOLOCATION_LAT NUMBER(18,8),
  GEOLOCATION_LNG NUMBER(18,8),
  GEOLOCATION_CITY STRING,
  GEOLOCATION_STATE STRING,
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ
);

-- ---------------------------------------------------------------------
-- 2) Deterministic reload for learning runs
-- ---------------------------------------------------------------------

TRUNCATE TABLE BRONZE.BRZ_ORDERS;
TRUNCATE TABLE BRONZE.BRZ_ORDER_ITEMS;
TRUNCATE TABLE BRONZE.BRZ_CUSTOMERS;
TRUNCATE TABLE BRONZE.BRZ_SELLERS;
TRUNCATE TABLE BRONZE.BRZ_PRODUCTS;
TRUNCATE TABLE BRONZE.BRZ_PRODUCT_CATEGORY_TRANSLATION;
TRUNCATE TABLE BRONZE.BRZ_ORDER_PAYMENTS;
TRUNCATE TABLE BRONZE.BRZ_ORDER_REVIEWS;
TRUNCATE TABLE BRONZE.BRZ_GEOLOCATION;

-- ---------------------------------------------------------------------
-- 3) Landing -> Bronze typed inserts
-- ---------------------------------------------------------------------

INSERT INTO BRONZE.BRZ_ORDERS
SELECT
  ORDER_ID,
  CUSTOMER_ID,
  ORDER_STATUS,
  TRY_TO_TIMESTAMP_NTZ(ORDER_PURCHASE_TIMESTAMP) AS ORDER_PURCHASE_TS,
  TRY_TO_TIMESTAMP_NTZ(ORDER_APPROVED_AT) AS ORDER_APPROVED_TS,
  TRY_TO_TIMESTAMP_NTZ(ORDER_DELIVERED_CARRIER_DATE) AS ORDER_DELIVERED_CARRIER_TS,
  TRY_TO_TIMESTAMP_NTZ(ORDER_DELIVERED_CUSTOMER_DATE) AS ORDER_DELIVERED_CUSTOMER_TS,
  TRY_TO_TIMESTAMP_NTZ(ORDER_ESTIMATED_DELIVERY_DATE) AS ORDER_ESTIMATED_DELIVERY_TS,
  SRC_FILENAME,
  LOAD_TS
FROM LANDING.LND_ORDERS_RAW;

INSERT INTO BRONZE.BRZ_ORDER_ITEMS
SELECT
  ORDER_ID,
  TRY_TO_NUMBER(ORDER_ITEM_ID) AS ORDER_ITEM_ID,
  PRODUCT_ID,
  SELLER_ID,
  TRY_TO_TIMESTAMP_NTZ(SHIPPING_LIMIT_DATE) AS SHIPPING_LIMIT_TS,
  TRY_TO_NUMBER(PRICE, 18, 2) AS PRICE,
  TRY_TO_NUMBER(FREIGHT_VALUE, 18, 2) AS FREIGHT_VALUE,
  SRC_FILENAME,
  LOAD_TS
FROM LANDING.LND_ORDER_ITEMS_RAW;

INSERT INTO BRONZE.BRZ_CUSTOMERS
SELECT
  CUSTOMER_ID,
  CUSTOMER_UNIQUE_ID,
  CUSTOMER_ZIP_CODE_PREFIX,
  CUSTOMER_CITY,
  CUSTOMER_STATE,
  SRC_FILENAME,
  LOAD_TS
FROM LANDING.LND_CUSTOMERS_RAW;

INSERT INTO BRONZE.BRZ_SELLERS
SELECT
  SELLER_ID,
  SELLER_ZIP_CODE_PREFIX,
  SELLER_CITY,
  SELLER_STATE,
  SRC_FILENAME,
  LOAD_TS
FROM LANDING.LND_SELLERS_RAW;

INSERT INTO BRONZE.BRZ_PRODUCTS
SELECT
  PRODUCT_ID,
  PRODUCT_CATEGORY_NAME,
  TRY_TO_NUMBER(PRODUCT_NAME_LENGHT) AS PRODUCT_NAME_LENGTH,
  TRY_TO_NUMBER(PRODUCT_DESCRIPTION_LENGHT) AS PRODUCT_DESCRIPTION_LENGTH,
  TRY_TO_NUMBER(PRODUCT_PHOTOS_QTY) AS PRODUCT_PHOTOS_QTY,
  TRY_TO_NUMBER(PRODUCT_WEIGHT_G) AS PRODUCT_WEIGHT_G,
  TRY_TO_NUMBER(PRODUCT_LENGTH_CM) AS PRODUCT_LENGTH_CM,
  TRY_TO_NUMBER(PRODUCT_HEIGHT_CM) AS PRODUCT_HEIGHT_CM,
  TRY_TO_NUMBER(PRODUCT_WIDTH_CM) AS PRODUCT_WIDTH_CM,
  SRC_FILENAME,
  LOAD_TS
FROM LANDING.LND_PRODUCTS_RAW;

INSERT INTO BRONZE.BRZ_PRODUCT_CATEGORY_TRANSLATION
SELECT
  PRODUCT_CATEGORY_NAME,
  PRODUCT_CATEGORY_NAME_ENGLISH,
  SRC_FILENAME,
  LOAD_TS
FROM LANDING.LND_PRODUCT_CATEGORY_TRANSLATION_RAW;

INSERT INTO BRONZE.BRZ_ORDER_PAYMENTS
SELECT
  ORDER_ID,
  TRY_TO_NUMBER(PAYMENT_SEQUENTIAL) AS PAYMENT_SEQUENTIAL,
  PAYMENT_TYPE,
  TRY_TO_NUMBER(PAYMENT_INSTALLMENTS) AS PAYMENT_INSTALLMENTS,
  TRY_TO_NUMBER(PAYMENT_VALUE, 18, 2) AS PAYMENT_VALUE,
  SRC_FILENAME,
  LOAD_TS
FROM LANDING.LND_ORDER_PAYMENTS_RAW;

INSERT INTO BRONZE.BRZ_ORDER_REVIEWS
SELECT
  REVIEW_ID,
  ORDER_ID,
  TRY_TO_NUMBER(REVIEW_SCORE) AS REVIEW_SCORE,
  REVIEW_COMMENT_TITLE,
  REVIEW_COMMENT_MESSAGE,
  TRY_TO_TIMESTAMP_NTZ(REVIEW_CREATION_DATE) AS REVIEW_CREATION_TS,
  TRY_TO_TIMESTAMP_NTZ(REVIEW_ANSWER_TIMESTAMP) AS REVIEW_ANSWER_TS,
  SRC_FILENAME,
  LOAD_TS
FROM LANDING.LND_ORDER_REVIEWS_RAW;

INSERT INTO BRONZE.BRZ_GEOLOCATION
SELECT
  GEOLOCATION_ZIP_CODE_PREFIX,
  TRY_TO_NUMBER(GEOLOCATION_LAT, 18, 8) AS GEOLOCATION_LAT,
  TRY_TO_NUMBER(GEOLOCATION_LNG, 18, 8) AS GEOLOCATION_LNG,
  GEOLOCATION_CITY,
  GEOLOCATION_STATE,
  SRC_FILENAME,
  LOAD_TS
FROM LANDING.LND_GEOLOCATION_RAW;

-- ---------------------------------------------------------------------
-- 4) Quick validation: Landing vs Bronze row counts
-- ---------------------------------------------------------------------

SELECT 'LND_ORDERS_RAW' AS table_name, COUNT(*) AS row_count FROM LANDING.LND_ORDERS_RAW
UNION ALL SELECT 'BRZ_ORDERS', COUNT(*) FROM BRONZE.BRZ_ORDERS
UNION ALL SELECT 'LND_ORDER_ITEMS_RAW', COUNT(*) FROM LANDING.LND_ORDER_ITEMS_RAW
UNION ALL SELECT 'BRZ_ORDER_ITEMS', COUNT(*) FROM BRONZE.BRZ_ORDER_ITEMS
UNION ALL SELECT 'LND_CUSTOMERS_RAW', COUNT(*) FROM LANDING.LND_CUSTOMERS_RAW
UNION ALL SELECT 'BRZ_CUSTOMERS', COUNT(*) FROM BRONZE.BRZ_CUSTOMERS
UNION ALL SELECT 'LND_SELLERS_RAW', COUNT(*) FROM LANDING.LND_SELLERS_RAW
UNION ALL SELECT 'BRZ_SELLERS', COUNT(*) FROM BRONZE.BRZ_SELLERS
UNION ALL SELECT 'LND_PRODUCTS_RAW', COUNT(*) FROM LANDING.LND_PRODUCTS_RAW
UNION ALL SELECT 'BRZ_PRODUCTS', COUNT(*) FROM BRONZE.BRZ_PRODUCTS
UNION ALL SELECT 'LND_PRODUCT_CATEGORY_TRANSLATION_RAW', COUNT(*) FROM LANDING.LND_PRODUCT_CATEGORY_TRANSLATION_RAW
UNION ALL SELECT 'BRZ_PRODUCT_CATEGORY_TRANSLATION', COUNT(*) FROM BRONZE.BRZ_PRODUCT_CATEGORY_TRANSLATION
UNION ALL SELECT 'LND_ORDER_PAYMENTS_RAW', COUNT(*) FROM LANDING.LND_ORDER_PAYMENTS_RAW
UNION ALL SELECT 'BRZ_ORDER_PAYMENTS', COUNT(*) FROM BRONZE.BRZ_ORDER_PAYMENTS
UNION ALL SELECT 'LND_ORDER_REVIEWS_RAW', COUNT(*) FROM LANDING.LND_ORDER_REVIEWS_RAW
UNION ALL SELECT 'BRZ_ORDER_REVIEWS', COUNT(*) FROM BRONZE.BRZ_ORDER_REVIEWS
UNION ALL SELECT 'LND_GEOLOCATION_RAW', COUNT(*) FROM LANDING.LND_GEOLOCATION_RAW
UNION ALL SELECT 'BRZ_GEOLOCATION', COUNT(*) FROM BRONZE.BRZ_GEOLOCATION
ORDER BY 1;
