USE DATABASE FINANCE_DB;
USE SCHEMA BRONZE;

TRUNCATE TABLE BRONZE.BRZ_ORDERS;

INSERT INTO BRONZE.BRZ_ORDERS
SELECT
  ORDER_ID,
  CUSTOMER_ID,
  ORDER_STATUS,
  TRY_TO_TIMESTAMP_NTZ(ORDER_PURCHASE_TIMESTAMP) AS ORDER_PURCHASE_TS,
  TRY_TO_TIMESTAMP_NTZ(ORDER_APPROVED_AT) AS ORDER_APPROVED_TS,
  TRY_TO_TIMESTAMP_NTZ(ORDER_DELIVERED_CARRIER_DATE) AS ORDER_DELIVERED_CARRIER_TS,
  TRY_TO_TIMESTAMP_NTZ(ORDER_DELIVERED_CUSTOMER_DATE) AS ORDER_DELIVERED_CUSTOMER_TS,
  TRY_TO_TIMESTAMP_NTZ(ORDER_ESTIMATED_DELIVERY_DATE) AS ORDER_ESTIMATED_DELIVERY_TS,
  SRC_FILENAME,
  LOAD_TS
FROM LANDING.LND_ORDERS_RAW;
