USE DATABASE FINANCE_DB;
USE SCHEMA BRONZE;

TRUNCATE TABLE BRONZE.BRZ_ORDER_ITEMS;

INSERT INTO BRONZE.BRZ_ORDER_ITEMS
SELECT
  ORDER_ID,
  TRY_TO_NUMBER(ORDER_ITEM_ID) AS ORDER_ITEM_ID,
  PRODUCT_ID,
  SELLER_ID,
  TRY_TO_TIMESTAMP_NTZ(SHIPPING_LIMIT_DATE) AS SHIPPING_LIMIT_TS,
  TRY_TO_NUMBER(PRICE, 18, 2) AS PRICE,
  TRY_TO_NUMBER(FREIGHT_VALUE, 18, 2) AS FREIGHT_VALUE,
  SRC_FILENAME,
  LOAD_TS
FROM LANDING.LND_ORDER_ITEMS_RAW;
