USE DATABASE FINANCE_DB;
USE SCHEMA BRONZE;

TRUNCATE TABLE BRONZE.BRZ_CUSTOMERS;

INSERT INTO BRONZE.BRZ_CUSTOMERS
SELECT
  CUSTOMER_ID,
  CUSTOMER_UNIQUE_ID,
  CUSTOMER_ZIP_CODE_PREFIX,
  CUSTOMER_CITY,
  CUSTOMER_STATE,
  SRC_FILENAME,
  LOAD_TS
FROM LANDING.LND_CUSTOMERS_RAW;
