USE DATABASE FINANCE_DB;
USE SCHEMA BRONZE;

TRUNCATE TABLE BRONZE.BRZ_SELLERS;

INSERT INTO BRONZE.BRZ_SELLERS
SELECT
  SELLER_ID,
  SELLER_ZIP_CODE_PREFIX,
  SELLER_CITY,
  SELLER_STATE,
  SRC_FILENAME,
  LOAD_TS
FROM LANDING.LND_SELLERS_RAW;
