USE DATABASE FINANCE_DB;
USE SCHEMA BRONZE;

TRUNCATE TABLE BRONZE.BRZ_PRODUCTS;
TRUNCATE TABLE BRONZE.BRZ_PRODUCT_CATEGORY_TRANSLATION;

INSERT INTO BRONZE.BRZ_PRODUCTS
SELECT
  PRODUCT_ID,
  PRODUCT_CATEGORY_NAME,
  TRY_TO_NUMBER(PRODUCT_NAME_LENGHT) AS PRODUCT_NAME_LENGTH,
  TRY_TO_NUMBER(PRODUCT_DESCRIPTION_LENGHT) AS PRODUCT_DESCRIPTION_LENGTH,
  TRY_TO_NUMBER(PRODUCT_PHOTOS_QTY) AS PRODUCT_PHOTOS_QTY,
  TRY_TO_NUMBER(PRODUCT_WEIGHT_G) AS PRODUCT_WEIGHT_G,
  TRY_TO_NUMBER(PRODUCT_LENGTH_CM) AS PRODUCT_LENGTH_CM,
  TRY_TO_NUMBER(PRODUCT_HEIGHT_CM) AS PRODUCT_HEIGHT_CM,
  TRY_TO_NUMBER(PRODUCT_WIDTH_CM) AS PRODUCT_WIDTH_CM,
  SRC_FILENAME,
  LOAD_TS
FROM LANDING.LND_PRODUCTS_RAW;

INSERT INTO BRONZE.BRZ_PRODUCT_CATEGORY_TRANSLATION
SELECT
  PRODUCT_CATEGORY_NAME,
  PRODUCT_CATEGORY_NAME_ENGLISH,
  SRC_FILENAME,
  LOAD_TS
FROM LANDING.LND_PRODUCT_CATEGORY_TRANSLATION_RAW;
