USE DATABASE FINANCE_DB;
USE SCHEMA BRONZE;

TRUNCATE TABLE BRONZE.BRZ_ORDER_PAYMENTS;

INSERT INTO BRONZE.BRZ_ORDER_PAYMENTS
SELECT
  ORDER_ID,
  TRY_TO_NUMBER(PAYMENT_SEQUENTIAL) AS PAYMENT_SEQUENTIAL,
  PAYMENT_TYPE,
  TRY_TO_NUMBER(PAYMENT_INSTALLMENTS) AS PAYMENT_INSTALLMENTS,
  TRY_TO_NUMBER(PAYMENT_VALUE, 18, 2) AS PAYMENT_VALUE,
  SRC_FILENAME,
  LOAD_TS
FROM LANDING.LND_ORDER_PAYMENTS_RAW;
