USE DATABASE FINANCE_DB;
USE SCHEMA BRONZE;

TRUNCATE TABLE BRONZE.BRZ_ORDER_REVIEWS;

INSERT INTO BRONZE.BRZ_ORDER_REVIEWS
SELECT
  REVIEW_ID,
  ORDER_ID,
  TRY_TO_NUMBER(REVIEW_SCORE) AS REVIEW_SCORE,
  REVIEW_COMMENT_TITLE,
  REVIEW_COMMENT_MESSAGE,
  TRY_TO_TIMESTAMP_NTZ(REVIEW_CREATION_DATE) AS REVIEW_CREATION_TS,
  TRY_TO_TIMESTAMP_NTZ(REVIEW_ANSWER_TIMESTAMP) AS REVIEW_ANSWER_TS,
  SRC_FILENAME,
  LOAD_TS
FROM LANDING.LND_ORDER_REVIEWS_RAW;
