USE DATABASE FINANCE_DB;
USE SCHEMA BRONZE;

TRUNCATE TABLE BRONZE.BRZ_GEOLOCATION;

INSERT INTO BRONZE.BRZ_GEOLOCATION
SELECT
  GEOLOCATION_ZIP_CODE_PREFIX,
  TRY_TO_NUMBER(GEOLOCATION_LAT, 18, 8) AS GEOLOCATION_LAT,
  TRY_TO_NUMBER(GEOLOCATION_LNG, 18, 8) AS GEOLOCATION_LNG,
  GEOLOCATION_CITY,
  GEOLOCATION_STATE,
  SRC_FILENAME,
  LOAD_TS
FROM LANDING.LND_GEOLOCATION_RAW;
