USE DATABASE FINANCE_DB;

SELECT 'LND_ORDERS_RAW' AS table_name, COUNT(*) AS row_count FROM LANDING.LND_ORDERS_RAW
UNION ALL SELECT 'BRZ_ORDERS', COUNT(*) FROM BRONZE.BRZ_ORDERS
UNION ALL SELECT 'LND_ORDER_ITEMS_RAW', COUNT(*) FROM LANDING.LND_ORDER_ITEMS_RAW
UNION ALL SELECT 'BRZ_ORDER_ITEMS', COUNT(*) FROM BRONZE.BRZ_ORDER_ITEMS
UNION ALL SELECT 'LND_CUSTOMERS_RAW', COUNT(*) FROM LANDING.LND_CUSTOMERS_RAW
UNION ALL SELECT 'BRZ_CUSTOMERS', COUNT(*) FROM BRONZE.BRZ_CUSTOMERS
UNION ALL SELECT 'LND_SELLERS_RAW', COUNT(*) FROM LANDING.LND_SELLERS_RAW
UNION ALL SELECT 'BRZ_SELLERS', COUNT(*) FROM BRONZE.BRZ_SELLERS
UNION ALL SELECT 'LND_PRODUCTS_RAW', COUNT(*) FROM LANDING.LND_PRODUCTS_RAW
UNION ALL SELECT 'BRZ_PRODUCTS', COUNT(*) FROM BRONZE.BRZ_PRODUCTS
UNION ALL SELECT 'LND_PRODUCT_CATEGORY_TRANSLATION_RAW', COUNT(*) FROM LANDING.LND_PRODUCT_CATEGORY_TRANSLATION_RAW
UNION ALL SELECT 'BRZ_PRODUCT_CATEGORY_TRANSLATION', COUNT(*) FROM BRONZE.BRZ_PRODUCT_CATEGORY_TRANSLATION
UNION ALL SELECT 'LND_ORDER_PAYMENTS_RAW', COUNT(*) FROM LANDING.LND_ORDER_PAYMENTS_RAW
UNION ALL SELECT 'BRZ_ORDER_PAYMENTS', COUNT(*) FROM BRONZE.BRZ_ORDER_PAYMENTS
UNION ALL SELECT 'LND_ORDER_REVIEWS_RAW', COUNT(*) FROM LANDING.LND_ORDER_REVIEWS_RAW
UNION ALL SELECT 'BRZ_ORDER_REVIEWS', COUNT(*) FROM BRONZE.BRZ_ORDER_REVIEWS
UNION ALL SELECT 'LND_GEOLOCATION_RAW', COUNT(*) FROM LANDING.LND_GEOLOCATION_RAW
UNION ALL SELECT 'BRZ_GEOLOCATION', COUNT(*) FROM BRONZE.BRZ_GEOLOCATION
ORDER BY 1;
