-- 01_create_landing_and_copy_core_files.sql
-- Full landing ingestion for all 9 Olist source files

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE FINANCE_DB;
USE SCHEMA LANDING;

-- Landing tables keep raw strings + ingestion metadata.
CREATE TABLE IF NOT EXISTS LANDING.LND_ORDERS_RAW (
  ORDER_ID STRING,
  CUSTOMER_ID STRING,
  ORDER_STATUS STRING,
  ORDER_PURCHASE_TIMESTAMP STRING,
  ORDER_APPROVED_AT STRING,
  ORDER_DELIVERED_CARRIER_DATE STRING,
  ORDER_DELIVERED_CUSTOMER_DATE STRING,
  ORDER_ESTIMATED_DELIVERY_DATE STRING,
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS LANDING.LND_ORDER_ITEMS_RAW (
  ORDER_ID STRING,
  ORDER_ITEM_ID STRING,
  PRODUCT_ID STRING,
  SELLER_ID STRING,
  SHIPPING_LIMIT_DATE STRING,
  PRICE STRING,
  FREIGHT_VALUE STRING,
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS LANDING.LND_CUSTOMERS_RAW (
  CUSTOMER_ID STRING,
  CUSTOMER_UNIQUE_ID STRING,
  CUSTOMER_ZIP_CODE_PREFIX STRING,
  CUSTOMER_CITY STRING,
  CUSTOMER_STATE STRING,
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS LANDING.LND_SELLERS_RAW (
  SELLER_ID STRING,
  SELLER_ZIP_CODE_PREFIX STRING,
  SELLER_CITY STRING,
  SELLER_STATE STRING,
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS LANDING.LND_PRODUCTS_RAW (
  PRODUCT_ID STRING,
  PRODUCT_CATEGORY_NAME STRING,
  PRODUCT_NAME_LENGHT STRING,
  PRODUCT_DESCRIPTION_LENGHT STRING,
  PRODUCT_PHOTOS_QTY STRING,
  PRODUCT_WEIGHT_G STRING,
  PRODUCT_LENGTH_CM STRING,
  PRODUCT_HEIGHT_CM STRING,
  PRODUCT_WIDTH_CM STRING,
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS LANDING.LND_PRODUCT_CATEGORY_TRANSLATION_RAW (
  PRODUCT_CATEGORY_NAME STRING,
  PRODUCT_CATEGORY_NAME_ENGLISH STRING,
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS LANDING.LND_ORDER_PAYMENTS_RAW (
  ORDER_ID STRING,
  PAYMENT_SEQUENTIAL STRING,
  PAYMENT_TYPE STRING,
  PAYMENT_INSTALLMENTS STRING,
  PAYMENT_VALUE STRING,
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS LANDING.LND_ORDER_REVIEWS_RAW (
  REVIEW_ID STRING,
  ORDER_ID STRING,
  REVIEW_SCORE STRING,
  REVIEW_COMMENT_TITLE STRING,
  REVIEW_COMMENT_MESSAGE STRING,
  REVIEW_CREATION_DATE STRING,
  REVIEW_ANSWER_TIMESTAMP STRING,
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS LANDING.LND_GEOLOCATION_RAW (
  GEOLOCATION_ZIP_CODE_PREFIX STRING,
  GEOLOCATION_LAT STRING,
  GEOLOCATION_LNG STRING,
  GEOLOCATION_CITY STRING,
  GEOLOCATION_STATE STRING,
  SRC_FILENAME STRING,
  LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Optional: truncate before reload (keeps script deterministic for learning runs).
TRUNCATE TABLE LANDING.LND_ORDERS_RAW;
TRUNCATE TABLE LANDING.LND_ORDER_ITEMS_RAW;
TRUNCATE TABLE LANDING.LND_CUSTOMERS_RAW;
TRUNCATE TABLE LANDING.LND_SELLERS_RAW;
TRUNCATE TABLE LANDING.LND_PRODUCTS_RAW;
TRUNCATE TABLE LANDING.LND_PRODUCT_CATEGORY_TRANSLATION_RAW;
TRUNCATE TABLE LANDING.LND_ORDER_PAYMENTS_RAW;
TRUNCATE TABLE LANDING.LND_ORDER_REVIEWS_RAW;
TRUNCATE TABLE LANDING.LND_GEOLOCATION_RAW;

-- Orders
COPY INTO LANDING.LND_ORDERS_RAW
  (ORDER_ID, CUSTOMER_ID, ORDER_STATUS, ORDER_PURCHASE_TIMESTAMP, ORDER_APPROVED_AT,
   ORDER_DELIVERED_CARRIER_DATE, ORDER_DELIVERED_CUSTOMER_DATE, ORDER_ESTIMATED_DELIVERY_DATE,
   SRC_FILENAME)
FROM (
  SELECT
    t.$1, t.$2, t.$3, t.$4, t.$5, t.$6, t.$7, t.$8,
    METADATA$FILENAME
  FROM @FINANCE_DB.STAGE.RAW_CSV_STAGE/olist_orders_dataset.csv.gz t
)
FILE_FORMAT = (FORMAT_NAME = FINANCE_DB.STAGE.FF_CSV)
ON_ERROR = 'ABORT_STATEMENT';

-- Order items
COPY INTO LANDING.LND_ORDER_ITEMS_RAW
  (ORDER_ID, ORDER_ITEM_ID, PRODUCT_ID, SELLER_ID, SHIPPING_LIMIT_DATE, PRICE, FREIGHT_VALUE,
   SRC_FILENAME)
FROM (
  SELECT
    t.$1, t.$2, t.$3, t.$4, t.$5, t.$6, t.$7,
    METADATA$FILENAME
  FROM @FINANCE_DB.STAGE.RAW_CSV_STAGE/olist_order_items_dataset.csv.gz t
)
FILE_FORMAT = (FORMAT_NAME = FINANCE_DB.STAGE.FF_CSV)
ON_ERROR = 'ABORT_STATEMENT';

-- Customers
COPY INTO LANDING.LND_CUSTOMERS_RAW
  (CUSTOMER_ID, CUSTOMER_UNIQUE_ID, CUSTOMER_ZIP_CODE_PREFIX, CUSTOMER_CITY, CUSTOMER_STATE,
   SRC_FILENAME)
FROM (
  SELECT
    t.$1, t.$2, t.$3, t.$4, t.$5,
    METADATA$FILENAME
  FROM @FINANCE_DB.STAGE.RAW_CSV_STAGE/olist_customers_dataset.csv.gz t
)
FILE_FORMAT = (FORMAT_NAME = FINANCE_DB.STAGE.FF_CSV)
ON_ERROR = 'ABORT_STATEMENT';

-- Sellers
COPY INTO LANDING.LND_SELLERS_RAW
  (SELLER_ID, SELLER_ZIP_CODE_PREFIX, SELLER_CITY, SELLER_STATE, SRC_FILENAME)
FROM (
  SELECT
    t.$1, t.$2, t.$3, t.$4,
    METADATA$FILENAME
  FROM @FINANCE_DB.STAGE.RAW_CSV_STAGE/olist_sellers_dataset.csv.gz t
)
FILE_FORMAT = (FORMAT_NAME = FINANCE_DB.STAGE.FF_CSV)
ON_ERROR = 'ABORT_STATEMENT';

-- Products
COPY INTO LANDING.LND_PRODUCTS_RAW
  (PRODUCT_ID, PRODUCT_CATEGORY_NAME, PRODUCT_NAME_LENGHT, PRODUCT_DESCRIPTION_LENGHT,
   PRODUCT_PHOTOS_QTY, PRODUCT_WEIGHT_G, PRODUCT_LENGTH_CM, PRODUCT_HEIGHT_CM, PRODUCT_WIDTH_CM,
   SRC_FILENAME)
FROM (
  SELECT
    t.$1, t.$2, t.$3, t.$4, t.$5, t.$6, t.$7, t.$8, t.$9,
    METADATA$FILENAME
  FROM @FINANCE_DB.STAGE.RAW_CSV_STAGE/olist_products_dataset.csv.gz t
)
FILE_FORMAT = (FORMAT_NAME = FINANCE_DB.STAGE.FF_CSV)
ON_ERROR = 'ABORT_STATEMENT';

-- Category translation
COPY INTO LANDING.LND_PRODUCT_CATEGORY_TRANSLATION_RAW
  (PRODUCT_CATEGORY_NAME, PRODUCT_CATEGORY_NAME_ENGLISH, SRC_FILENAME)
FROM (
  SELECT
    t.$1, t.$2,
    METADATA$FILENAME
  FROM @FINANCE_DB.STAGE.RAW_CSV_STAGE/product_category_name_translation.csv.gz t
)
FILE_FORMAT = (FORMAT_NAME = FINANCE_DB.STAGE.FF_CSV)
ON_ERROR = 'ABORT_STATEMENT';

-- Payments
COPY INTO LANDING.LND_ORDER_PAYMENTS_RAW
  (ORDER_ID, PAYMENT_SEQUENTIAL, PAYMENT_TYPE, PAYMENT_INSTALLMENTS, PAYMENT_VALUE, SRC_FILENAME)
FROM (
  SELECT
    t.$1, t.$2, t.$3, t.$4, t.$5,
    METADATA$FILENAME
  FROM @FINANCE_DB.STAGE.RAW_CSV_STAGE/olist_order_payments_dataset.csv.gz t
)
FILE_FORMAT = (FORMAT_NAME = FINANCE_DB.STAGE.FF_CSV)
ON_ERROR = 'ABORT_STATEMENT';

-- Reviews
COPY INTO LANDING.LND_ORDER_REVIEWS_RAW
  (REVIEW_ID, ORDER_ID, REVIEW_SCORE, REVIEW_COMMENT_TITLE, REVIEW_COMMENT_MESSAGE,
   REVIEW_CREATION_DATE, REVIEW_ANSWER_TIMESTAMP, SRC_FILENAME)
FROM (
  SELECT
    t.$1, t.$2, t.$3, t.$4, t.$5, t.$6, t.$7,
    METADATA$FILENAME
  FROM @FINANCE_DB.STAGE.RAW_CSV_STAGE/olist_order_reviews_dataset.csv.gz t
)
FILE_FORMAT = (FORMAT_NAME = FINANCE_DB.STAGE.FF_CSV)
ON_ERROR = 'ABORT_STATEMENT';

-- Geolocation
COPY INTO LANDING.LND_GEOLOCATION_RAW
  (GEOLOCATION_ZIP_CODE_PREFIX, GEOLOCATION_LAT, GEOLOCATION_LNG, GEOLOCATION_CITY, GEOLOCATION_STATE,
   SRC_FILENAME)
FROM (
  SELECT
    t.$1, t.$2, t.$3, t.$4, t.$5,
    METADATA$FILENAME
  FROM @FINANCE_DB.STAGE.RAW_CSV_STAGE/olist_geolocation_dataset.csv.gz t
)
FILE_FORMAT = (FORMAT_NAME = FINANCE_DB.STAGE.FF_CSV)
ON_ERROR = 'ABORT_STATEMENT';

-- Quick checks
SELECT 'LND_ORDERS_RAW' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM LANDING.LND_ORDERS_RAW
UNION ALL
SELECT 'LND_ORDER_ITEMS_RAW', COUNT(*) FROM LANDING.LND_ORDER_ITEMS_RAW
UNION ALL
SELECT 'LND_CUSTOMERS_RAW', COUNT(*) FROM LANDING.LND_CUSTOMERS_RAW
UNION ALL
SELECT 'LND_SELLERS_RAW', COUNT(*) FROM LANDING.LND_SELLERS_RAW
UNION ALL
SELECT 'LND_PRODUCTS_RAW', COUNT(*) FROM LANDING.LND_PRODUCTS_RAW
UNION ALL
SELECT 'LND_PRODUCT_CATEGORY_TRANSLATION_RAW', COUNT(*) FROM LANDING.LND_PRODUCT_CATEGORY_TRANSLATION_RAW
UNION ALL
SELECT 'LND_ORDER_PAYMENTS_RAW', COUNT(*) FROM LANDING.LND_ORDER_PAYMENTS_RAW
UNION ALL
SELECT 'LND_ORDER_REVIEWS_RAW', COUNT(*) FROM LANDING.LND_ORDER_REVIEWS_RAW
UNION ALL
SELECT 'LND_GEOLOCATION_RAW', COUNT(*) FROM LANDING.LND_GEOLOCATION_RAW
ORDER BY 1;
