USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE FINANCE_DB;
CREATE SCHEMA IF NOT EXISTS CONTROL;
USE SCHEMA CONTROL;

CREATE TABLE IF NOT EXISTS CONTROL.DQ_CHECK_RESULTS (
  RUN_ID STRING,
  CHECK_TS TIMESTAMP_NTZ,
  CHECK_GROUP STRING,
  CHECK_NAME STRING,
  STATUS STRING,
  METRIC_VALUE NUMBER(38,6),
  EXPECTED_VALUE NUMBER(38,6),
  NOTE STRING
);

CREATE OR REPLACE PROCEDURE CONTROL.SP_RUN_DQ(P_RUN_ID STRING)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  INSERT INTO CONTROL.DQ_CHECK_RESULTS
  SELECT :P_RUN_ID, CURRENT_TIMESTAMP(), 'ROW_PARITY', 'BRZ_ORDERS_EQ_SLV_ORDERS',
         IFF(b = s, 'PASS', 'FAIL'), b, s,
         'Bronze vs Silver row count parity'
  FROM (
    SELECT (SELECT COUNT(*) FROM BRONZE.BRZ_ORDERS) b,
           (SELECT COUNT(*) FROM SILVER.SLV_ORDERS) s
  );

  INSERT INTO CONTROL.DQ_CHECK_RESULTS
  SELECT :P_RUN_ID, CURRENT_TIMESTAMP(), 'GOLD_RECON',
         'DAILY_MONTHLY_REVENUE_DIFF_' || COALESCE(d.ym,m.ym),
         IFF(ABS(COALESCE(d.rev,0)-COALESCE(m.rev,0)) < 0.01, 'PASS', 'FAIL'),
         ABS(COALESCE(d.rev,0)-COALESCE(m.rev,0)),
         0,
         'Daily vs monthly revenue reconciliation'
  FROM (
    SELECT TO_CHAR(ORDER_DATE, 'YYYY-MM') ym, SUM(REVENUE) rev
    FROM GOLD.KPI_DAILY_REVENUE
    GROUP BY 1
  ) d
  FULL OUTER JOIN (
    SELECT YEAR_MONTH ym, SUM(REVENUE) rev
    FROM GOLD.KPI_MONTHLY_REVENUE
    GROUP BY 1
  ) m
  ON d.ym = m.ym;

  RETURN 'DQ completed';
END;
$$;
