-- 01_create_db_schema.sql
-- Bootstrap core database and medallion/control schemas

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE DATABASE IF NOT EXISTS FINANCE_DB;

CREATE SCHEMA IF NOT EXISTS FINANCE_DB.STAGE;
CREATE SCHEMA IF NOT EXISTS FINANCE_DB.LANDING;
CREATE SCHEMA IF NOT EXISTS FINANCE_DB.BRONZE;
CREATE SCHEMA IF NOT EXISTS FINANCE_DB.SILVER;
CREATE SCHEMA IF NOT EXISTS FINANCE_DB.GOLD;
CREATE SCHEMA IF NOT EXISTS FINANCE_DB.CONTROL;
CREATE SCHEMA IF NOT EXISTS FINANCE_DB.AUDIT;
CREATE SCHEMA IF NOT EXISTS FINANCE_DB.ERROR;
CREATE SCHEMA IF NOT EXISTS FINANCE_DB.METADATA;
CREATE SCHEMA IF NOT EXISTS FINANCE_DB.ML;

-- Quick visibility check
SHOW SCHEMAS IN DATABASE FINANCE_DB;
