USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE FINANCE_DB;

-- Cost-safe warehouse defaults
ALTER WAREHOUSE COMPUTE_WH SET AUTO_SUSPEND = 60;
ALTER WAREHOUSE COMPUTE_WH SET AUTO_RESUME = TRUE;

CREATE SCHEMA IF NOT EXISTS OPS;

CREATE OR REPLACE PROCEDURE OPS.SP_PIPELINE_RUN()
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
  V_RUN_ID STRING DEFAULT UUID_STRING();
BEGIN
  CALL FINANCE_DB.AUDIT.SP_LOG_RUN_START(:V_RUN_ID, 'ops_incremental_pipeline');
  CALL FINANCE_DB.SILVER.SP_APPLY_SILVER_INCREMENTAL();
  CALL FINANCE_DB.GOLD.SP_APPLY_GOLD_INCREMENTAL();
  CALL FINANCE_DB.CONTROL.SP_RUN_DQ(:V_RUN_ID);
  CALL FINANCE_DB.AUDIT.SP_LOG_RUN_END(:V_RUN_ID, 'SUCCESS', 'Incremental ETL + DQ completed');

  RETURN :V_RUN_ID;
EXCEPTION
  WHEN OTHER THEN
    CALL FINANCE_DB.AUDIT.SP_LOG_RUN_END(:V_RUN_ID, 'FAILED', 'Unhandled error in SP_PIPELINE_RUN');
    CALL FINANCE_DB.AUDIT.SP_SEND_FAILURE_EMAIL(:V_RUN_ID, 'Unhandled error in SP_PIPELINE_RUN');
    RETURN :V_RUN_ID;
END;
$$;

-- Manual task (on-demand smoke run)
CREATE OR REPLACE TASK OPS.TASK_PIPELINE_RUN_MANUAL
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON * * * * * UTC'
AS
  CALL OPS.SP_PIPELINE_RUN();

-- Auto-triggered task: runs only when Bronze streams have data.
CREATE OR REPLACE TASK OPS.TASK_PIPELINE_RUN_AUTO
  WAREHOUSE = COMPUTE_WH
  WHEN
    SYSTEM$STREAM_HAS_DATA('FINANCE_DB.BRONZE.STR_BRZ_ORDERS')
    OR SYSTEM$STREAM_HAS_DATA('FINANCE_DB.BRONZE.STR_BRZ_ORDER_ITEMS')
    OR SYSTEM$STREAM_HAS_DATA('FINANCE_DB.BRONZE.STR_BRZ_CUSTOMERS')
    OR SYSTEM$STREAM_HAS_DATA('FINANCE_DB.BRONZE.STR_BRZ_SELLERS')
    OR SYSTEM$STREAM_HAS_DATA('FINANCE_DB.BRONZE.STR_BRZ_PRODUCTS')
    OR SYSTEM$STREAM_HAS_DATA('FINANCE_DB.BRONZE.STR_BRZ_PRODUCT_CATEGORY_TRANSLATION')
    OR SYSTEM$STREAM_HAS_DATA('FINANCE_DB.BRONZE.STR_BRZ_ORDER_PAYMENTS')
    OR SYSTEM$STREAM_HAS_DATA('FINANCE_DB.BRONZE.STR_BRZ_ORDER_REVIEWS')
    OR SYSTEM$STREAM_HAS_DATA('FINANCE_DB.BRONZE.STR_BRZ_GEOLOCATION')
AS
  CALL OPS.SP_PIPELINE_RUN();

-- Keep manual scheduler suspended by default; auto task active for event-driven runs.
ALTER TASK OPS.TASK_PIPELINE_RUN_MANUAL SUSPEND;
ALTER TASK OPS.TASK_PIPELINE_RUN_AUTO RESUME;

SHOW TASKS IN SCHEMA FINANCE_DB.OPS;
