USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE FINANCE_DB;

-- Bronze CDC streams: used to drive incremental Silver merges
CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE OR REPLACE STREAM FINANCE_DB.BRONZE.STR_BRZ_ORDERS ON TABLE FINANCE_DB.BRONZE.BRZ_ORDERS;
CREATE OR REPLACE STREAM FINANCE_DB.BRONZE.STR_BRZ_ORDER_ITEMS ON TABLE FINANCE_DB.BRONZE.BRZ_ORDER_ITEMS;
CREATE OR REPLACE STREAM FINANCE_DB.BRONZE.STR_BRZ_CUSTOMERS ON TABLE FINANCE_DB.BRONZE.BRZ_CUSTOMERS;
CREATE OR REPLACE STREAM FINANCE_DB.BRONZE.STR_BRZ_SELLERS ON TABLE FINANCE_DB.BRONZE.BRZ_SELLERS;
CREATE OR REPLACE STREAM FINANCE_DB.BRONZE.STR_BRZ_PRODUCTS ON TABLE FINANCE_DB.BRONZE.BRZ_PRODUCTS;
CREATE OR REPLACE STREAM FINANCE_DB.BRONZE.STR_BRZ_PRODUCT_CATEGORY_TRANSLATION ON TABLE FINANCE_DB.BRONZE.BRZ_PRODUCT_CATEGORY_TRANSLATION;
CREATE OR REPLACE STREAM FINANCE_DB.BRONZE.STR_BRZ_ORDER_PAYMENTS ON TABLE FINANCE_DB.BRONZE.BRZ_ORDER_PAYMENTS;
CREATE OR REPLACE STREAM FINANCE_DB.BRONZE.STR_BRZ_ORDER_REVIEWS ON TABLE FINANCE_DB.BRONZE.BRZ_ORDER_REVIEWS;
CREATE OR REPLACE STREAM FINANCE_DB.BRONZE.STR_BRZ_GEOLOCATION ON TABLE FINANCE_DB.BRONZE.BRZ_GEOLOCATION;

-- Silver CDC streams: used to drive incremental Gold refresh
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE OR REPLACE STREAM FINANCE_DB.SILVER.STR_SLV_ORDERS ON TABLE FINANCE_DB.SILVER.SLV_ORDERS;
CREATE OR REPLACE STREAM FINANCE_DB.SILVER.STR_SLV_ORDER_ITEMS ON TABLE FINANCE_DB.SILVER.SLV_ORDER_ITEMS;
CREATE OR REPLACE STREAM FINANCE_DB.SILVER.STR_SLV_CUSTOMERS ON TABLE FINANCE_DB.SILVER.SLV_CUSTOMERS;
CREATE OR REPLACE STREAM FINANCE_DB.SILVER.STR_SLV_SELLERS ON TABLE FINANCE_DB.SILVER.SLV_SELLERS;
CREATE OR REPLACE STREAM FINANCE_DB.SILVER.STR_SLV_PRODUCTS ON TABLE FINANCE_DB.SILVER.SLV_PRODUCTS;
CREATE OR REPLACE STREAM FINANCE_DB.SILVER.STR_SLV_ORDER_PAYMENTS ON TABLE FINANCE_DB.SILVER.SLV_ORDER_PAYMENTS;
CREATE OR REPLACE STREAM FINANCE_DB.SILVER.STR_SLV_ORDER_REVIEWS ON TABLE FINANCE_DB.SILVER.SLV_ORDER_REVIEWS;

SHOW STREAMS IN SCHEMA FINANCE_DB.BRONZE;
SHOW STREAMS IN SCHEMA FINANCE_DB.SILVER;
