USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE FINANCE_DB;
CREATE SCHEMA IF NOT EXISTS AUDIT;
USE SCHEMA AUDIT;

CREATE TABLE IF NOT EXISTS AUDIT.PIPELINE_RUN_LOG (
  RUN_ID STRING,
  PIPELINE_NAME STRING,
  STARTED_AT TIMESTAMP_NTZ,
  ENDED_AT TIMESTAMP_NTZ,
  STATUS STRING,
  NOTE STRING,
  INSERTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE PROCEDURE AUDIT.SP_LOG_RUN_START(P_RUN_ID STRING, P_PIPELINE_NAME STRING)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  INSERT INTO AUDIT.PIPELINE_RUN_LOG (
    RUN_ID, PIPELINE_NAME, STARTED_AT, STATUS, NOTE
  )
  VALUES (
    :P_RUN_ID, :P_PIPELINE_NAME, CURRENT_TIMESTAMP(), 'RUNNING', 'Task run started'
  );
  RETURN 'RUN_START_LOGGED';
END;
$$;

CREATE OR REPLACE PROCEDURE AUDIT.SP_LOG_RUN_END(P_RUN_ID STRING, P_STATUS STRING, P_NOTE STRING)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  UPDATE AUDIT.PIPELINE_RUN_LOG
  SET ENDED_AT = CURRENT_TIMESTAMP(),
      STATUS = :P_STATUS,
      NOTE = :P_NOTE
  WHERE RUN_ID = :P_RUN_ID;
  RETURN 'RUN_END_LOGGED';
END;
$$;
