USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE FINANCE_DB;
CREATE SCHEMA IF NOT EXISTS AUDIT;

CREATE TABLE IF NOT EXISTS AUDIT.ALERT_CONFIG (
  ALERT_NAME STRING,
  EMAIL_INTEGRATION STRING,
  RECIPIENT_EMAIL STRING,
  IS_ACTIVE BOOLEAN,
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Keep one active row; update with your real integration/email.
MERGE INTO AUDIT.ALERT_CONFIG t
USING (
  SELECT
    'PIPELINE_FAILURE' AS ALERT_NAME,
    'FINANCE_EMAIL_INT' AS EMAIL_INTEGRATION,
    'replace-me@example.com' AS RECIPIENT_EMAIL,
    FALSE AS IS_ACTIVE
) s
ON t.ALERT_NAME = s.ALERT_NAME
WHEN MATCHED THEN UPDATE SET
  EMAIL_INTEGRATION = s.EMAIL_INTEGRATION,
  RECIPIENT_EMAIL = s.RECIPIENT_EMAIL,
  IS_ACTIVE = s.IS_ACTIVE,
  UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
  ALERT_NAME, EMAIL_INTEGRATION, RECIPIENT_EMAIL, IS_ACTIVE
) VALUES (
  s.ALERT_NAME, s.EMAIL_INTEGRATION, s.RECIPIENT_EMAIL, s.IS_ACTIVE
);

CREATE OR REPLACE PROCEDURE AUDIT.SP_SEND_FAILURE_EMAIL(P_RUN_ID STRING, P_NOTE STRING)
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
  V_INT STRING;
  V_EMAIL STRING;
  V_SUBJECT STRING;
  V_BODY STRING;
BEGIN
  SELECT EMAIL_INTEGRATION, RECIPIENT_EMAIL
    INTO :V_INT, :V_EMAIL
  FROM AUDIT.ALERT_CONFIG
  WHERE ALERT_NAME = 'PIPELINE_FAILURE' AND IS_ACTIVE = TRUE
  LIMIT 1;

  IF (V_INT IS NULL OR V_EMAIL IS NULL) THEN
    RETURN 'ALERT_SKIPPED_CONFIG_INACTIVE';
  END IF;

  V_SUBJECT := 'FINANCE_DB pipeline failed | run_id=' || P_RUN_ID;
  V_BODY := 'Run ID: ' || P_RUN_ID || '\nStatus: FAILED\nNote: ' || COALESCE(P_NOTE,'') || '\nTimestamp: ' || CURRENT_TIMESTAMP();

  CALL SYSTEM$SEND_EMAIL(V_INT, V_EMAIL, V_SUBJECT, V_BODY);
  RETURN 'ALERT_SENT';

EXCEPTION
  WHEN OTHER THEN
    RETURN 'ALERT_SEND_FAILED';
END;
$$;
