USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE FINANCE_DB;
USE SCHEMA GOLD;

CREATE TABLE IF NOT EXISTS GOLD.KPI_DAILY_REVENUE (
  ORDER_DATE DATE,
  REVENUE NUMBER(18,2),
  ORDERS NUMBER,
  UNIQUE_CUSTOMERS NUMBER
);

CREATE TABLE IF NOT EXISTS GOLD.KPI_MONTHLY_REVENUE (
  YEAR_MONTH STRING,
  MONTH_START_DATE DATE,
  REVENUE NUMBER(18,2),
  ORDERS NUMBER,
  UNIQUE_CUSTOMERS NUMBER,
  REPEAT_ORDER_DELTA NUMBER,
  ORDERS_PER_CUSTOMER NUMBER(18,6),
  AVG_ORDER_VALUE NUMBER(18,2)
);

CREATE TABLE IF NOT EXISTS GOLD.KPI_CUSTOMER_RFM (
  CUSTOMER_ID STRING,
  RECENCY_DAYS NUMBER,
  FREQUENCY NUMBER,
  MONETARY NUMBER(18,2),
  LAST_ORDER_DATE DATE,
  RFM_SEGMENT STRING
);

CREATE TABLE IF NOT EXISTS GOLD.KPI_PAYMENT_SUMMARY (
  YEAR_MONTH STRING,
  PAYMENT_TYPE STRING,
  TOTAL_PAYMENT_VALUE NUMBER(18,2),
  PAYMENT_TXN_COUNT NUMBER,
  AVG_INSTALLMENTS NUMBER(18,4)
);

CREATE TABLE IF NOT EXISTS GOLD.KPI_DELIVERY_SLA (
  YEAR_MONTH STRING,
  TOTAL_DELIVERED_ORDERS NUMBER,
  ON_TIME_ORDERS NUMBER,
  LATE_ORDERS NUMBER,
  ON_TIME_PCT NUMBER(18,4),
  AVG_DELAY_DAYS NUMBER(18,4)
);

CREATE TABLE IF NOT EXISTS GOLD.KPI_SELLER_PERFORMANCE (
  SELLER_ID STRING,
  SELLER_STATE STRING,
  ORDERS NUMBER,
  REVENUE NUMBER(18,2),
  AVG_REVIEW_SCORE NUMBER(18,4)
);

CREATE TABLE IF NOT EXISTS GOLD.KPI_CATEGORY_PERFORMANCE (
  PRODUCT_CATEGORY_NAME_ENGLISH STRING,
  ORDERS NUMBER,
  REVENUE NUMBER(18,2),
  AVG_ITEM_REVENUE NUMBER(18,2)
);

CREATE TABLE IF NOT EXISTS GOLD.KPI_REGION_PERFORMANCE (
  CUSTOMER_STATE STRING,
  ORDERS NUMBER,
  UNIQUE_CUSTOMERS NUMBER,
  REVENUE NUMBER(18,2)
);
