USE DATABASE FINANCE_DB;
USE SCHEMA GOLD;

TRUNCATE TABLE GOLD.KPI_DAILY_REVENUE;

INSERT INTO GOLD.KPI_DAILY_REVENUE
SELECT
  o.ORDER_PURCHASE_TS::DATE AS ORDER_DATE,
  SUM(i.REVENUE) AS REVENUE,
  COUNT(DISTINCT o.ORDER_ID) AS ORDERS,
  COUNT(DISTINCT o.CUSTOMER_ID) AS UNIQUE_CUSTOMERS
FROM SILVER.SLV_ORDERS o
JOIN SILVER.SLV_ORDER_ITEMS i ON i.ORDER_ID = o.ORDER_ID
WHERE o.ORDER_STATUS = 'delivered'
  AND o.ORDER_PURCHASE_TS IS NOT NULL
GROUP BY 1
ORDER BY 1;
