USE DATABASE FINANCE_DB;
USE SCHEMA GOLD;

TRUNCATE TABLE GOLD.KPI_MONTHLY_REVENUE;

INSERT INTO GOLD.KPI_MONTHLY_REVENUE
SELECT
  TO_CHAR(o.ORDER_PURCHASE_TS::DATE, 'YYYY-MM') AS YEAR_MONTH,
  DATE_TRUNC('month', o.ORDER_PURCHASE_TS::DATE) AS MONTH_START_DATE,
  SUM(i.REVENUE) AS REVENUE,
  COUNT(DISTINCT o.ORDER_ID) AS ORDERS,
  COUNT(DISTINCT o.CUSTOMER_ID) AS UNIQUE_CUSTOMERS,
  COUNT(DISTINCT o.ORDER_ID) - COUNT(DISTINCT o.CUSTOMER_ID) AS REPEAT_ORDER_DELTA,
  COUNT(DISTINCT o.ORDER_ID)::FLOAT / NULLIF(COUNT(DISTINCT o.CUSTOMER_ID),0) AS ORDERS_PER_CUSTOMER,
  SUM(i.REVENUE) / NULLIF(COUNT(DISTINCT o.ORDER_ID),0) AS AVG_ORDER_VALUE
FROM SILVER.SLV_ORDERS o
JOIN SILVER.SLV_ORDER_ITEMS i ON i.ORDER_ID = o.ORDER_ID
WHERE o.ORDER_STATUS = 'delivered'
  AND o.ORDER_PURCHASE_TS IS NOT NULL
GROUP BY 1,2
ORDER BY 2;
