USE DATABASE FINANCE_DB;
USE SCHEMA GOLD;

TRUNCATE TABLE GOLD.KPI_CUSTOMER_RFM;

INSERT INTO GOLD.KPI_CUSTOMER_RFM
WITH base AS (
  SELECT
    o.CUSTOMER_ID,
    MAX(o.ORDER_PURCHASE_TS::DATE) AS LAST_ORDER_DATE,
    COUNT(DISTINCT o.ORDER_ID) AS FREQUENCY,
    SUM(i.REVENUE) AS MONETARY
  FROM SILVER.SLV_ORDERS o
  JOIN SILVER.SLV_ORDER_ITEMS i ON i.ORDER_ID = o.ORDER_ID
  WHERE o.ORDER_STATUS = 'delivered'
  GROUP BY 1
), mx AS (
  SELECT MAX(LAST_ORDER_DATE) AS MAX_ORDER_DATE FROM base
)
SELECT
  b.CUSTOMER_ID,
  DATEDIFF('day', b.LAST_ORDER_DATE, m.MAX_ORDER_DATE) AS RECENCY_DAYS,
  b.FREQUENCY,
  b.MONETARY,
  b.LAST_ORDER_DATE,
  CASE
    WHEN b.MONETARY >= 500 THEN 'HIGH_VALUE'
    WHEN b.MONETARY >= 200 THEN 'MEDIUM_VALUE'
    ELSE 'LOW_VALUE'
  END AS RFM_SEGMENT
FROM base b
CROSS JOIN mx m;
