USE DATABASE FINANCE_DB;
USE SCHEMA GOLD;

TRUNCATE TABLE GOLD.KPI_PAYMENT_SUMMARY;

INSERT INTO GOLD.KPI_PAYMENT_SUMMARY
SELECT
  TO_CHAR(o.ORDER_PURCHASE_TS::DATE, 'YYYY-MM') AS YEAR_MONTH,
  p.PAYMENT_TYPE,
  SUM(p.PAYMENT_VALUE) AS TOTAL_PAYMENT_VALUE,
  COUNT(*) AS PAYMENT_TXN_COUNT,
  AVG(p.PAYMENT_INSTALLMENTS) AS AVG_INSTALLMENTS
FROM SILVER.SLV_ORDER_PAYMENTS p
JOIN SILVER.SLV_ORDERS o ON o.ORDER_ID = p.ORDER_ID
WHERE o.ORDER_PURCHASE_TS IS NOT NULL
GROUP BY 1,2
ORDER BY 1,2;
