USE DATABASE FINANCE_DB;
USE SCHEMA GOLD;

TRUNCATE TABLE GOLD.KPI_DELIVERY_SLA;

INSERT INTO GOLD.KPI_DELIVERY_SLA
SELECT
  TO_CHAR(ORDER_PURCHASE_TS::DATE, 'YYYY-MM') AS YEAR_MONTH,
  COUNT(*) AS TOTAL_DELIVERED_ORDERS,
  SUM(IFF(COALESCE(DELIVERY_DELAY_DAYS,0) <= 0, 1, 0)) AS ON_TIME_ORDERS,
  SUM(IFF(COALESCE(DELIVERY_DELAY_DAYS,0) > 0, 1, 0)) AS LATE_ORDERS,
  SUM(IFF(COALESCE(DELIVERY_DELAY_DAYS,0) <= 0, 1, 0))::FLOAT / NULLIF(COUNT(*),0) AS ON_TIME_PCT,
  AVG(COALESCE(DELIVERY_DELAY_DAYS,0)) AS AVG_DELAY_DAYS
FROM SILVER.SLV_ORDERS
WHERE ORDER_STATUS = 'delivered'
  AND ORDER_PURCHASE_TS IS NOT NULL
GROUP BY 1
ORDER BY 1;
