USE DATABASE FINANCE_DB;
USE SCHEMA GOLD;

TRUNCATE TABLE GOLD.KPI_SELLER_PERFORMANCE;

INSERT INTO GOLD.KPI_SELLER_PERFORMANCE
SELECT
  i.SELLER_ID,
  s.SELLER_STATE,
  COUNT(DISTINCT i.ORDER_ID) AS ORDERS,
  SUM(i.REVENUE) AS REVENUE,
  AVG(r.REVIEW_SCORE) AS AVG_REVIEW_SCORE
FROM SILVER.SLV_ORDER_ITEMS i
LEFT JOIN SILVER.SLV_SELLERS s ON s.SELLER_ID = i.SELLER_ID
LEFT JOIN SILVER.SLV_ORDER_REVIEWS r ON r.ORDER_ID = i.ORDER_ID
GROUP BY 1,2
ORDER BY REVENUE DESC;
