USE DATABASE FINANCE_DB;
USE SCHEMA GOLD;

TRUNCATE TABLE GOLD.KPI_CATEGORY_PERFORMANCE;

INSERT INTO GOLD.KPI_CATEGORY_PERFORMANCE
SELECT
  COALESCE(p.PRODUCT_CATEGORY_NAME_ENGLISH, 'UNKNOWN') AS PRODUCT_CATEGORY_NAME_ENGLISH,
  COUNT(DISTINCT i.ORDER_ID) AS ORDERS,
  SUM(i.REVENUE) AS REVENUE,
  AVG(i.REVENUE) AS AVG_ITEM_REVENUE
FROM SILVER.SLV_ORDER_ITEMS i
LEFT JOIN SILVER.SLV_PRODUCTS p ON p.PRODUCT_ID = i.PRODUCT_ID
GROUP BY 1
ORDER BY REVENUE DESC;
