USE DATABASE FINANCE_DB;
USE SCHEMA GOLD;

TRUNCATE TABLE GOLD.KPI_REGION_PERFORMANCE;

INSERT INTO GOLD.KPI_REGION_PERFORMANCE
SELECT
  c.CUSTOMER_STATE,
  COUNT(DISTINCT o.ORDER_ID) AS ORDERS,
  COUNT(DISTINCT o.CUSTOMER_ID) AS UNIQUE_CUSTOMERS,
  SUM(i.REVENUE) AS REVENUE
FROM SILVER.SLV_ORDERS o
JOIN SILVER.SLV_CUSTOMERS c ON c.CUSTOMER_ID = o.CUSTOMER_ID
JOIN SILVER.SLV_ORDER_ITEMS i ON i.ORDER_ID = o.ORDER_ID
WHERE o.ORDER_STATUS = 'delivered'
GROUP BY 1
ORDER BY REVENUE DESC;
