USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE FINANCE_DB;

CREATE OR REPLACE PROCEDURE FINANCE_DB.GOLD.SP_REBUILD_GOLD()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  TRUNCATE TABLE FINANCE_DB.GOLD.KPI_DAILY_REVENUE;
  INSERT INTO FINANCE_DB.GOLD.KPI_DAILY_REVENUE
  SELECT o.ORDER_PURCHASE_TS::DATE, SUM(i.REVENUE), COUNT(DISTINCT o.ORDER_ID), COUNT(DISTINCT o.CUSTOMER_ID)
  FROM FINANCE_DB.SILVER.SLV_ORDERS o
  JOIN FINANCE_DB.SILVER.SLV_ORDER_ITEMS i ON i.ORDER_ID = o.ORDER_ID
  WHERE o.ORDER_STATUS = 'delivered' AND o.ORDER_PURCHASE_TS IS NOT NULL
  GROUP BY 1;

  TRUNCATE TABLE FINANCE_DB.GOLD.KPI_MONTHLY_REVENUE;
  INSERT INTO FINANCE_DB.GOLD.KPI_MONTHLY_REVENUE
  SELECT TO_CHAR(o.ORDER_PURCHASE_TS::DATE, 'YYYY-MM'), DATE_TRUNC('month', o.ORDER_PURCHASE_TS::DATE),
         SUM(i.REVENUE), COUNT(DISTINCT o.ORDER_ID), COUNT(DISTINCT o.CUSTOMER_ID),
         COUNT(DISTINCT o.ORDER_ID) - COUNT(DISTINCT o.CUSTOMER_ID),
         COUNT(DISTINCT o.ORDER_ID)::FLOAT / NULLIF(COUNT(DISTINCT o.CUSTOMER_ID),0),
         SUM(i.REVENUE) / NULLIF(COUNT(DISTINCT o.ORDER_ID),0)
  FROM FINANCE_DB.SILVER.SLV_ORDERS o
  JOIN FINANCE_DB.SILVER.SLV_ORDER_ITEMS i ON i.ORDER_ID = o.ORDER_ID
  WHERE o.ORDER_STATUS = 'delivered' AND o.ORDER_PURCHASE_TS IS NOT NULL
  GROUP BY 1,2;

  TRUNCATE TABLE FINANCE_DB.GOLD.KPI_CUSTOMER_RFM;
  INSERT INTO FINANCE_DB.GOLD.KPI_CUSTOMER_RFM
  WITH base AS (
    SELECT o.CUSTOMER_ID,
           MAX(o.ORDER_PURCHASE_TS::DATE) AS LAST_ORDER_DATE,
           COUNT(DISTINCT o.ORDER_ID) AS FREQUENCY,
           SUM(i.REVENUE) AS MONETARY
    FROM FINANCE_DB.SILVER.SLV_ORDERS o
    JOIN FINANCE_DB.SILVER.SLV_ORDER_ITEMS i ON i.ORDER_ID = o.ORDER_ID
    WHERE o.ORDER_STATUS = 'delivered'
    GROUP BY 1
  ), mx AS (
    SELECT MAX(LAST_ORDER_DATE) AS MAX_ORDER_DATE FROM base
  )
  SELECT b.CUSTOMER_ID,
         DATEDIFF('day', b.LAST_ORDER_DATE, m.MAX_ORDER_DATE),
         b.FREQUENCY,
         b.MONETARY,
         b.LAST_ORDER_DATE,
         CASE WHEN b.MONETARY >= 500 THEN 'HIGH_VALUE'
              WHEN b.MONETARY >= 200 THEN 'MEDIUM_VALUE'
              ELSE 'LOW_VALUE' END
  FROM base b
  CROSS JOIN mx m;

  TRUNCATE TABLE FINANCE_DB.GOLD.KPI_PAYMENT_SUMMARY;
  INSERT INTO FINANCE_DB.GOLD.KPI_PAYMENT_SUMMARY
  SELECT TO_CHAR(o.ORDER_PURCHASE_TS::DATE, 'YYYY-MM'),
         p.PAYMENT_TYPE,
         SUM(p.PAYMENT_VALUE),
         COUNT(*),
         AVG(p.PAYMENT_INSTALLMENTS)
  FROM FINANCE_DB.SILVER.SLV_ORDER_PAYMENTS p
  JOIN FINANCE_DB.SILVER.SLV_ORDERS o ON o.ORDER_ID = p.ORDER_ID
  WHERE o.ORDER_PURCHASE_TS IS NOT NULL
  GROUP BY 1,2;

  TRUNCATE TABLE FINANCE_DB.GOLD.KPI_DELIVERY_SLA;
  INSERT INTO FINANCE_DB.GOLD.KPI_DELIVERY_SLA
  SELECT TO_CHAR(ORDER_PURCHASE_TS::DATE, 'YYYY-MM'),
         COUNT(*),
         SUM(IFF(COALESCE(DELIVERY_DELAY_DAYS,0) <= 0, 1, 0)),
         SUM(IFF(COALESCE(DELIVERY_DELAY_DAYS,0) > 0, 1, 0)),
         SUM(IFF(COALESCE(DELIVERY_DELAY_DAYS,0) <= 0, 1, 0))::FLOAT / NULLIF(COUNT(*),0),
         AVG(COALESCE(DELIVERY_DELAY_DAYS,0))
  FROM FINANCE_DB.SILVER.SLV_ORDERS
  WHERE ORDER_STATUS = 'delivered' AND ORDER_PURCHASE_TS IS NOT NULL
  GROUP BY 1;

  TRUNCATE TABLE FINANCE_DB.GOLD.KPI_SELLER_PERFORMANCE;
  INSERT INTO FINANCE_DB.GOLD.KPI_SELLER_PERFORMANCE
  SELECT i.SELLER_ID,
         s.SELLER_STATE,
         COUNT(DISTINCT i.ORDER_ID),
         SUM(i.REVENUE),
         AVG(r.REVIEW_SCORE)
  FROM FINANCE_DB.SILVER.SLV_ORDER_ITEMS i
  LEFT JOIN FINANCE_DB.SILVER.SLV_SELLERS s ON s.SELLER_ID = i.SELLER_ID
  LEFT JOIN FINANCE_DB.SILVER.SLV_ORDER_REVIEWS r ON r.ORDER_ID = i.ORDER_ID
  GROUP BY 1,2;

  TRUNCATE TABLE FINANCE_DB.GOLD.KPI_CATEGORY_PERFORMANCE;
  INSERT INTO FINANCE_DB.GOLD.KPI_CATEGORY_PERFORMANCE
  SELECT COALESCE(p.PRODUCT_CATEGORY_NAME_ENGLISH, 'UNKNOWN'),
         COUNT(DISTINCT i.ORDER_ID),
         SUM(i.REVENUE),
         AVG(i.REVENUE)
  FROM FINANCE_DB.SILVER.SLV_ORDER_ITEMS i
  LEFT JOIN FINANCE_DB.SILVER.SLV_PRODUCTS p ON p.PRODUCT_ID = i.PRODUCT_ID
  GROUP BY 1;

  TRUNCATE TABLE FINANCE_DB.GOLD.KPI_REGION_PERFORMANCE;
  INSERT INTO FINANCE_DB.GOLD.KPI_REGION_PERFORMANCE
  SELECT c.CUSTOMER_STATE,
         COUNT(DISTINCT o.ORDER_ID),
         COUNT(DISTINCT o.CUSTOMER_ID),
         SUM(i.REVENUE)
  FROM FINANCE_DB.SILVER.SLV_ORDERS o
  JOIN FINANCE_DB.SILVER.SLV_CUSTOMERS c ON c.CUSTOMER_ID = o.CUSTOMER_ID
  JOIN FINANCE_DB.SILVER.SLV_ORDER_ITEMS i ON i.ORDER_ID = o.ORDER_ID
  WHERE o.ORDER_STATUS = 'delivered'
  GROUP BY 1;

  RETURN 'GOLD_REBUILT';
END;
$$;
