USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE FINANCE_DB;

CREATE OR REPLACE PROCEDURE FINANCE_DB.GOLD.SP_APPLY_GOLD_INCREMENTAL()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
  CREATE OR REPLACE TEMP TABLE TMP_CHANGED_ORDER_IDS AS
  SELECT DISTINCT ORDER_ID FROM FINANCE_DB.SILVER.STR_SLV_ORDERS WHERE METADATA$ACTION IN ('INSERT','UPDATE')
  UNION
  SELECT DISTINCT ORDER_ID FROM FINANCE_DB.SILVER.STR_SLV_ORDER_ITEMS WHERE METADATA$ACTION IN ('INSERT','UPDATE')
  UNION
  SELECT DISTINCT ORDER_ID FROM FINANCE_DB.SILVER.STR_SLV_ORDER_PAYMENTS WHERE METADATA$ACTION IN ('INSERT','UPDATE')
  UNION
  SELECT DISTINCT ORDER_ID FROM FINANCE_DB.SILVER.STR_SLV_ORDER_REVIEWS WHERE METADATA$ACTION IN ('INSERT','UPDATE');

  CREATE OR REPLACE TEMP TABLE TMP_CHANGED_DATES AS
  SELECT DISTINCT o.ORDER_PURCHASE_TS::DATE AS ORDER_DATE
  FROM FINANCE_DB.SILVER.SLV_ORDERS o
  JOIN TMP_CHANGED_ORDER_IDS c ON c.ORDER_ID = o.ORDER_ID
  WHERE o.ORDER_PURCHASE_TS IS NOT NULL;

  CREATE OR REPLACE TEMP TABLE TMP_CHANGED_MONTHS AS
  SELECT DISTINCT TO_CHAR(ORDER_DATE, 'YYYY-MM') AS YEAR_MONTH
  FROM TMP_CHANGED_DATES;

  CREATE OR REPLACE TEMP TABLE TMP_CHANGED_CUSTOMERS AS
  SELECT DISTINCT o.CUSTOMER_ID
  FROM FINANCE_DB.SILVER.SLV_ORDERS o
  JOIN TMP_CHANGED_ORDER_IDS c ON c.ORDER_ID = o.ORDER_ID
  WHERE o.CUSTOMER_ID IS NOT NULL
  UNION
  SELECT DISTINCT CUSTOMER_ID
  FROM FINANCE_DB.SILVER.STR_SLV_CUSTOMERS
  WHERE METADATA$ACTION IN ('INSERT','UPDATE');

  CREATE OR REPLACE TEMP TABLE TMP_CHANGED_SELLERS AS
  SELECT DISTINCT i.SELLER_ID
  FROM FINANCE_DB.SILVER.SLV_ORDER_ITEMS i
  JOIN TMP_CHANGED_ORDER_IDS c ON c.ORDER_ID = i.ORDER_ID
  WHERE i.SELLER_ID IS NOT NULL
  UNION
  SELECT DISTINCT SELLER_ID
  FROM FINANCE_DB.SILVER.STR_SLV_SELLERS
  WHERE METADATA$ACTION IN ('INSERT','UPDATE');

  CREATE OR REPLACE TEMP TABLE TMP_CHANGED_PRODUCTS AS
  SELECT DISTINCT i.PRODUCT_ID
  FROM FINANCE_DB.SILVER.SLV_ORDER_ITEMS i
  JOIN TMP_CHANGED_ORDER_IDS c ON c.ORDER_ID = i.ORDER_ID
  WHERE i.PRODUCT_ID IS NOT NULL
  UNION
  SELECT DISTINCT PRODUCT_ID
  FROM FINANCE_DB.SILVER.STR_SLV_PRODUCTS
  WHERE METADATA$ACTION IN ('INSERT','UPDATE');

  CREATE OR REPLACE TEMP TABLE TMP_CHANGED_STATES AS
  SELECT DISTINCT c.CUSTOMER_STATE
  FROM FINANCE_DB.SILVER.SLV_CUSTOMERS c
  JOIN FINANCE_DB.SILVER.SLV_ORDERS o ON o.CUSTOMER_ID = c.CUSTOMER_ID
  JOIN TMP_CHANGED_ORDER_IDS x ON x.ORDER_ID = o.ORDER_ID
  WHERE c.CUSTOMER_STATE IS NOT NULL;

  -- KPI_DAILY_REVENUE incremental
  DELETE FROM FINANCE_DB.GOLD.KPI_DAILY_REVENUE
  WHERE ORDER_DATE IN (SELECT ORDER_DATE FROM TMP_CHANGED_DATES);

  INSERT INTO FINANCE_DB.GOLD.KPI_DAILY_REVENUE
  SELECT o.ORDER_PURCHASE_TS::DATE AS ORDER_DATE,
         SUM(i.REVENUE) AS REVENUE,
         COUNT(DISTINCT o.ORDER_ID) AS ORDERS,
         COUNT(DISTINCT o.CUSTOMER_ID) AS UNIQUE_CUSTOMERS
  FROM FINANCE_DB.SILVER.SLV_ORDERS o
  JOIN FINANCE_DB.SILVER.SLV_ORDER_ITEMS i ON i.ORDER_ID = o.ORDER_ID
  WHERE o.ORDER_STATUS = 'delivered'
    AND o.ORDER_PURCHASE_TS::DATE IN (SELECT ORDER_DATE FROM TMP_CHANGED_DATES)
  GROUP BY 1;

  -- KPI_MONTHLY_REVENUE incremental
  DELETE FROM FINANCE_DB.GOLD.KPI_MONTHLY_REVENUE
  WHERE YEAR_MONTH IN (SELECT YEAR_MONTH FROM TMP_CHANGED_MONTHS);

  INSERT INTO FINANCE_DB.GOLD.KPI_MONTHLY_REVENUE
  SELECT TO_CHAR(o.ORDER_PURCHASE_TS::DATE, 'YYYY-MM') AS YEAR_MONTH,
         DATE_TRUNC('month', o.ORDER_PURCHASE_TS::DATE) AS MONTH_START_DATE,
         SUM(i.REVENUE) AS REVENUE,
         COUNT(DISTINCT o.ORDER_ID) AS ORDERS,
         COUNT(DISTINCT o.CUSTOMER_ID) AS UNIQUE_CUSTOMERS,
         COUNT(DISTINCT o.ORDER_ID) - COUNT(DISTINCT o.CUSTOMER_ID) AS REPEAT_ORDER_DELTA,
         COUNT(DISTINCT o.ORDER_ID)::FLOAT / NULLIF(COUNT(DISTINCT o.CUSTOMER_ID),0) AS ORDERS_PER_CUSTOMER,
         SUM(i.REVENUE) / NULLIF(COUNT(DISTINCT o.ORDER_ID),0) AS AVG_ORDER_VALUE
  FROM FINANCE_DB.SILVER.SLV_ORDERS o
  JOIN FINANCE_DB.SILVER.SLV_ORDER_ITEMS i ON i.ORDER_ID = o.ORDER_ID
  WHERE o.ORDER_STATUS = 'delivered'
    AND TO_CHAR(o.ORDER_PURCHASE_TS::DATE, 'YYYY-MM') IN (SELECT YEAR_MONTH FROM TMP_CHANGED_MONTHS)
  GROUP BY 1,2;

  -- KPI_CUSTOMER_RFM incremental
  DELETE FROM FINANCE_DB.GOLD.KPI_CUSTOMER_RFM
  WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM TMP_CHANGED_CUSTOMERS);

  INSERT INTO FINANCE_DB.GOLD.KPI_CUSTOMER_RFM
  WITH mx AS (
    SELECT MAX(ORDER_PURCHASE_TS::DATE) AS MAX_ORDER_DATE
    FROM FINANCE_DB.SILVER.SLV_ORDERS
    WHERE ORDER_STATUS = 'delivered'
  )
  SELECT o.CUSTOMER_ID,
         DATEDIFF('day', MAX(o.ORDER_PURCHASE_TS::DATE), m.MAX_ORDER_DATE) AS RECENCY_DAYS,
         COUNT(DISTINCT o.ORDER_ID) AS FREQUENCY,
         SUM(i.REVENUE) AS MONETARY,
         MAX(o.ORDER_PURCHASE_TS::DATE) AS LAST_ORDER_DATE,
         CASE
           WHEN SUM(i.REVENUE) >= 500 THEN 'HIGH_VALUE'
           WHEN SUM(i.REVENUE) >= 200 THEN 'MEDIUM_VALUE'
           ELSE 'LOW_VALUE'
         END AS RFM_SEGMENT
  FROM FINANCE_DB.SILVER.SLV_ORDERS o
  JOIN FINANCE_DB.SILVER.SLV_ORDER_ITEMS i ON i.ORDER_ID = o.ORDER_ID
  CROSS JOIN mx m
  WHERE o.ORDER_STATUS = 'delivered'
    AND o.CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM TMP_CHANGED_CUSTOMERS)
  GROUP BY o.CUSTOMER_ID, m.MAX_ORDER_DATE;

  -- KPI_PAYMENT_SUMMARY incremental
  DELETE FROM FINANCE_DB.GOLD.KPI_PAYMENT_SUMMARY
  WHERE YEAR_MONTH IN (SELECT YEAR_MONTH FROM TMP_CHANGED_MONTHS);

  INSERT INTO FINANCE_DB.GOLD.KPI_PAYMENT_SUMMARY
  SELECT TO_CHAR(o.ORDER_PURCHASE_TS::DATE, 'YYYY-MM') AS YEAR_MONTH,
         p.PAYMENT_TYPE,
         SUM(p.PAYMENT_VALUE) AS TOTAL_PAYMENT_VALUE,
         COUNT(*) AS PAYMENT_TXN_COUNT,
         AVG(p.PAYMENT_INSTALLMENTS) AS AVG_INSTALLMENTS
  FROM FINANCE_DB.SILVER.SLV_ORDER_PAYMENTS p
  JOIN FINANCE_DB.SILVER.SLV_ORDERS o ON o.ORDER_ID = p.ORDER_ID
  WHERE TO_CHAR(o.ORDER_PURCHASE_TS::DATE, 'YYYY-MM') IN (SELECT YEAR_MONTH FROM TMP_CHANGED_MONTHS)
  GROUP BY 1,2;

  -- KPI_DELIVERY_SLA incremental
  DELETE FROM FINANCE_DB.GOLD.KPI_DELIVERY_SLA
  WHERE YEAR_MONTH IN (SELECT YEAR_MONTH FROM TMP_CHANGED_MONTHS);

  INSERT INTO FINANCE_DB.GOLD.KPI_DELIVERY_SLA
  SELECT TO_CHAR(ORDER_PURCHASE_TS::DATE, 'YYYY-MM') AS YEAR_MONTH,
         COUNT(*) AS TOTAL_DELIVERED_ORDERS,
         SUM(IFF(COALESCE(DELIVERY_DELAY_DAYS,0) <= 0, 1, 0)) AS ON_TIME_ORDERS,
         SUM(IFF(COALESCE(DELIVERY_DELAY_DAYS,0) > 0, 1, 0)) AS LATE_ORDERS,
         SUM(IFF(COALESCE(DELIVERY_DELAY_DAYS,0) <= 0, 1, 0))::FLOAT / NULLIF(COUNT(*),0) AS ON_TIME_PCT,
         AVG(COALESCE(DELIVERY_DELAY_DAYS,0)) AS AVG_DELAY_DAYS
  FROM FINANCE_DB.SILVER.SLV_ORDERS
  WHERE ORDER_STATUS = 'delivered'
    AND TO_CHAR(ORDER_PURCHASE_TS::DATE, 'YYYY-MM') IN (SELECT YEAR_MONTH FROM TMP_CHANGED_MONTHS)
  GROUP BY 1;

  -- KPI_SELLER_PERFORMANCE incremental
  DELETE FROM FINANCE_DB.GOLD.KPI_SELLER_PERFORMANCE
  WHERE SELLER_ID IN (SELECT SELLER_ID FROM TMP_CHANGED_SELLERS);

  INSERT INTO FINANCE_DB.GOLD.KPI_SELLER_PERFORMANCE
  SELECT i.SELLER_ID,
         s.SELLER_STATE,
         COUNT(DISTINCT i.ORDER_ID) AS ORDERS,
         SUM(i.REVENUE) AS REVENUE,
         AVG(r.REVIEW_SCORE) AS AVG_REVIEW_SCORE
  FROM FINANCE_DB.SILVER.SLV_ORDER_ITEMS i
  LEFT JOIN FINANCE_DB.SILVER.SLV_SELLERS s ON s.SELLER_ID = i.SELLER_ID
  LEFT JOIN FINANCE_DB.SILVER.SLV_ORDER_REVIEWS r ON r.ORDER_ID = i.ORDER_ID
  WHERE i.SELLER_ID IN (SELECT SELLER_ID FROM TMP_CHANGED_SELLERS)
  GROUP BY 1,2;

  -- KPI_CATEGORY_PERFORMANCE incremental
  DELETE FROM FINANCE_DB.GOLD.KPI_CATEGORY_PERFORMANCE
  WHERE PRODUCT_CATEGORY_NAME_ENGLISH IN (
    SELECT DISTINCT COALESCE(p.PRODUCT_CATEGORY_NAME_ENGLISH, 'UNKNOWN')
    FROM FINANCE_DB.SILVER.SLV_PRODUCTS p
    WHERE p.PRODUCT_ID IN (SELECT PRODUCT_ID FROM TMP_CHANGED_PRODUCTS)
  );

  INSERT INTO FINANCE_DB.GOLD.KPI_CATEGORY_PERFORMANCE
  SELECT COALESCE(p.PRODUCT_CATEGORY_NAME_ENGLISH, 'UNKNOWN') AS PRODUCT_CATEGORY_NAME_ENGLISH,
         COUNT(DISTINCT i.ORDER_ID) AS ORDERS,
         SUM(i.REVENUE) AS REVENUE,
         AVG(i.REVENUE) AS AVG_ITEM_REVENUE
  FROM FINANCE_DB.SILVER.SLV_ORDER_ITEMS i
  LEFT JOIN FINANCE_DB.SILVER.SLV_PRODUCTS p ON p.PRODUCT_ID = i.PRODUCT_ID
  WHERE i.PRODUCT_ID IN (SELECT PRODUCT_ID FROM TMP_CHANGED_PRODUCTS)
  GROUP BY 1;

  -- KPI_REGION_PERFORMANCE incremental
  DELETE FROM FINANCE_DB.GOLD.KPI_REGION_PERFORMANCE
  WHERE CUSTOMER_STATE IN (SELECT CUSTOMER_STATE FROM TMP_CHANGED_STATES);

  INSERT INTO FINANCE_DB.GOLD.KPI_REGION_PERFORMANCE
  SELECT c.CUSTOMER_STATE,
         COUNT(DISTINCT o.ORDER_ID) AS ORDERS,
         COUNT(DISTINCT o.CUSTOMER_ID) AS UNIQUE_CUSTOMERS,
         SUM(i.REVENUE) AS REVENUE
  FROM FINANCE_DB.SILVER.SLV_ORDERS o
  JOIN FINANCE_DB.SILVER.SLV_CUSTOMERS c ON c.CUSTOMER_ID = o.CUSTOMER_ID
  JOIN FINANCE_DB.SILVER.SLV_ORDER_ITEMS i ON i.ORDER_ID = o.ORDER_ID
  WHERE o.ORDER_STATUS = 'delivered'
    AND c.CUSTOMER_STATE IN (SELECT CUSTOMER_STATE FROM TMP_CHANGED_STATES)
  GROUP BY 1;

  RETURN 'GOLD_INCREMENTAL_APPLIED';
END;
$$;
