USE DATABASE FINANCE_DB;
USE SCHEMA GOLD;

SELECT 'KPI_DAILY_REVENUE rowcount > 0' AS check_name, IFF(COUNT(*) > 0, 'PASS', 'FAIL') AS status, COUNT(*) AS metric
FROM KPI_DAILY_REVENUE
UNION ALL
SELECT 'KPI_MONTHLY_REVENUE rowcount > 0', IFF(COUNT(*) > 0, 'PASS', 'FAIL'), COUNT(*)
FROM KPI_MONTHLY_REVENUE
UNION ALL
SELECT 'KPI_CUSTOMER_RFM rowcount > 0', IFF(COUNT(*) > 0, 'PASS', 'FAIL'), COUNT(*)
FROM KPI_CUSTOMER_RFM
UNION ALL
SELECT 'KPI_PAYMENT_SUMMARY rowcount > 0', IFF(COUNT(*) > 0, 'PASS', 'FAIL'), COUNT(*)
FROM KPI_PAYMENT_SUMMARY
UNION ALL
SELECT 'KPI_DELIVERY_SLA rowcount > 0', IFF(COUNT(*) > 0, 'PASS', 'FAIL'), COUNT(*)
FROM KPI_DELIVERY_SLA
UNION ALL
SELECT 'KPI_SELLER_PERFORMANCE rowcount > 0', IFF(COUNT(*) > 0, 'PASS', 'FAIL'), COUNT(*)
FROM KPI_SELLER_PERFORMANCE
UNION ALL
SELECT 'KPI_CATEGORY_PERFORMANCE rowcount > 0', IFF(COUNT(*) > 0, 'PASS', 'FAIL'), COUNT(*)
FROM KPI_CATEGORY_PERFORMANCE
UNION ALL
SELECT 'KPI_REGION_PERFORMANCE rowcount > 0', IFF(COUNT(*) > 0, 'PASS', 'FAIL'), COUNT(*)
FROM KPI_REGION_PERFORMANCE;
